=== phreborn/vbfcp_comb/cfg/lhchcg/Orgnization.dtd
<!ELEMENT Orgnization (Item+)*>
<!ATTLIST Orgnization
        InFile              CDATA            #REQUIRED
        OutFile             CDATA            #REQUIRED
        ModelName           CDATA            #REQUIRED
        POINames            CDATA            #REQUIRED
> 
<!ELEMENT Item (Name)*>
<!ATTLIST Item
        Name              CDATA            #REQUIRED
>

=== phreborn/vbfcp_comb/cfg/lhchcg/CMS_param_BR_lumi_zz_template.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="#INPUT#" OutFile="#OUTPUT#"
	     ModelName="param_BR"
	     POINames="MH,mu_zz">
  <Item Name="zero[0]"/>
  <Item Name="one[1]"/>

  <!-- Introducing kappa values -->
  <!-- H->zz -->
  <Item Name="kappa_value_BR_param_alphaS_zz[1.012]"/>
  <Item Name="kappa_value_BR_param_mB_zz[0.981]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hqq_zz[0.988]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hvv_zz[1.004]"/>

  <Item Name="expr::log_kappa_value_LHC_LUMI_2011('sqrt(log(1+@0*@0))', uncert_LUMI_2011_correlate[0.006])"/>
  <Item Name="expr::log_kappa_value_LHC_LUMI_2012('sqrt(log(1+@0*@0))', uncert_LUMI_2012_correlate[0.021])"/>
  <Item Name="expr::log_kappa_value_CMS_LUMI_uncor_2011('sqrt(log(1+@0*@0))', uncert_LUMI_2011_uncorrelate[0.021])"/>
  <Item Name="expr::log_kappa_value_CMS_LUMI_uncor_2012('sqrt(log(1+@0*@0))', uncert_LUMI_2012_uncorrelate[0.015])"/>

  <!-- Introducing nuisance parameter names -->
  <Item Name="BR_param_alphaS[0,-5,5]"/>
  <Item Name="BR_param_mB[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hvv[0,-5,5]"/>

  <Item Name="LHC_LUMI_2011[0,-5,5]"/>
  <Item Name="LHC_LUMI_2012[0,-5,5]"/>
  <Item Name="CMS_LUMI_uncor_2011[0,-5,5]"/>
  <Item Name="CMS_LUMI_uncor_2012[0,-5,5]"/>

  <!-- Introducing global observables -->
  <Item Name="BR_param_alphaS_In[0]"/>
  <Item Name="BR_param_mB_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hvv_In[0]"/>

  <Item Name="LHC_LUMI_2011_In[0]"/>
  <Item Name="LHC_LUMI_2012_In[0]"/>
  <Item Name="CMS_LUMI_uncor_2011_In[0]"/>
  <Item Name="CMS_LUMI_uncor_2012_In[0]"/>

  <!-- Introducing constraint terms -->
  <Item Name="RooGaussian::BR_param_alphaS_Pdf(BR_param_alphaS,BR_param_alphaS_In,1)"/>
  <Item Name="RooGaussian::BR_param_mB_Pdf(BR_param_mB,BR_param_mB_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hqq_Pdf(BR_HiggsDecayWidthTHU_hqq,BR_HiggsDecayWidthTHU_hqq_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hvv_Pdf(BR_HiggsDecayWidthTHU_hvv,BR_HiggsDecayWidthTHU_hvv_In,1)"/>

  <Item Name="RooGaussian::LHC_LUMI_2011_Pdf(LHC_LUMI_2011,LHC_LUMI_2011_In,1)"/>
  <Item Name="RooGaussian::LHC_LUMI_2012_Pdf(LHC_LUMI_2012,LHC_LUMI_2012_In,1)"/>
  <Item Name="RooGaussian::CMS_LUMI_uncor_2011_Pdf(CMS_LUMI_uncor_2011,CMS_LUMI_uncor_2011_In,1)"/>
  <Item Name="RooGaussian::CMS_LUMI_uncor_2012_Pdf(CMS_LUMI_uncor_2012,CMS_LUMI_uncor_2012_In,1)"/>

  <!-- Introducing response terms -->
  <!-- H->zz -->
  <Item Name="prod::expected_BR_param_alphaS_zz(RooExponential::expTerm_BR_param_alphaS_zz(BR_param_alphaS, expr::log_kappa_value_BR_param_alphaS_zz('log(@0)', kappa_value_BR_param_alphaS_zz)),nominal_BR_param_alphaS_zz[1])"/>
  <Item Name="prod::expected_BR_param_mB_zz(RooExponential::expTerm_BR_param_mB_zz(BR_param_mB, expr::log_kappa_value_BR_param_mB_zz('log(@0)', kappa_value_BR_param_mB_zz)),nominal_BR_param_mB_zz[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hqq_zz(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hqq_zz(BR_HiggsDecayWidthTHU_hqq, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hqq_zz('log(@0)', kappa_value_BR_HiggsDecayWidthTHU_hqq_zz)),nominal_BR_HiggsDecayWidthTHU_hqq_zz[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hvv_zz(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hvv_zz(BR_HiggsDecayWidthTHU_hvv, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hvv_zz('log(@0)', kappa_value_BR_HiggsDecayWidthTHU_hvv_zz)),nominal_BR_HiggsDecayWidthTHU_hvv_zz[1])"/>

  <Item Name="prod::expected_LHC_LUMI_2011(RooExponential::expTerm_LHC_LUMI_2011(LHC_LUMI_2011, log_kappa_value_LHC_LUMI_2011),nominal_LHC_LUMI_2011[1])"/>
  <Item Name="prod::expected_LHC_LUMI_2012(RooExponential::expTerm_LHC_LUMI_2012(LHC_LUMI_2012, log_kappa_value_LHC_LUMI_2012),nominal_LHC_LUMI_2012[1])"/>
  <Item Name="prod::expected_CMS_LUMI_uncor_2011(RooExponential::expTerm_CMS_LUMI_uncor_2011(CMS_LUMI_uncor_2011, log_kappa_value_CMS_LUMI_uncor_2011),nominal_CMS_LUMI_uncor_2011[1])"/>
  <Item Name="prod::expected_CMS_LUMI_uncor_2012(RooExponential::expTerm_CMS_LUMI_uncor_2012(CMS_LUMI_uncor_2012, log_kappa_value_CMS_LUMI_uncor_2012),nominal_CMS_LUMI_uncor_2012[1])"/>

  <Item Name="prod:expected_BR_zz_new(expected_BR_param_alphaS_zz,expected_BR_param_mB_zz,expected_BR_HiggsDecayWidthTHU_hqq_zz,expected_BR_HiggsDecayWidthTHU_hvv_zz, expected_LHC_LUMI_2011, expected_LHC_LUMI_2012, expected_CMS_LUMI_uncor_2011, expected_CMS_LUMI_uncor_2012, ,mu_BR_ZZ[1])"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
       	       BRhiggs_ZZ4l=zero,
	       lumi_7TeV=zero,
	       lumi_8TeV=zero,
	       BRhiggs_ZZ4l_Pdf=one,
	       lumi_7TeV_Pdf=one,
	       lumi_8TeV_Pdf=one,
	       mu_BR_ZZ_temp=expected_BR_zz_new,
       	       )" />
</Orgnization>

=== phreborn/vbfcp_comb/cfg/lhchcg/ATLAS_measurement_parametrization_zz_obs.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="workspace/lhchcg/myrep/atlas/decorated/atlas_h4l_obs_decorated.root" OutFile="workspace/lhchcg/myrep/atlas/handler/atlas_h4l_obs_handler.root"
	     ModelName="param_BR"
	     POINames="mH,mu_ZZ,mu,lambda_mu,lambda_mu_ZZ,dmH_exp">

  <Item Name="mu[1]"/>
  <Item Name="mu_ZZ[1,-5,5]"/>

  <!-- <Item Name="mu_BR_gamgam_temp[1]"/> -->

  <!-- <Item Name="prod::RF_comp(RF_gg,mu_BR_gamgam_temp)"/> -->
  <!-- <Item Name="prod::RV_comp(RV_gg,mu_BR_gamgam_temp)"/> -->

  <Item Name="lambda_mu[1]"/>
  <Item Name="lambda_mu_ZZ[1]"/>

  <Item Name="dmH_exp[0]"/>

  <Item Name="mH[125,120,130]"/>  
  <Item Name="prod::mu_ZZ_comp(mu_ZZ,mu,lambda_mu_ZZ,lambda_mu)"/>

  <Item Name="sum::mH_comp(mH,dmH_exp)"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
	       mH=mH_comp,
	       mu=mu_ZZ_comp,
       	       )" />
</Orgnization>

=== phreborn/vbfcp_comb/cfg/lhchcg/atlas_v0/ATLAS_param_BR_zz_asimov.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="workspace/lhchcg/myrep/atlas/handler/atlas_h4l_asimov_handler.root" OutFile="workspace/lhchcg/myrep/atlas/parambr/atlas_h4l_asimov_parambr.root"
	     ModelName="param_BR"
	     POINames="MH,mu_zz">
  <Item Name="zero[0]"/>
  <Item Name="one[1]"/>

  <!-- Introducing kappa values -->
  <!-- H->zz -->
  <Item Name="kappa_value_BR_param_alphaS_zz[1.012]"/>
  <Item Name="kappa_value_BR_param_mB_zz[0.981]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hqq_zz[0.988]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hvv_zz[1.004]"/>

  <!-- Introducing nuisance parameter names -->
  <Item Name="BR_param_alphaS[0,-5,5]"/>
  <Item Name="BR_param_mB[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hvv[0,-5,5]"/>

  <!-- Introducing global observables -->
  <Item Name="BR_param_alphaS_In[0]"/>
  <Item Name="BR_param_mB_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hvv_In[0]"/>

  <!-- Introducing constraint terms -->
  <Item Name="RooGaussian::BR_param_alphaS_Pdf(BR_param_alphaS,BR_param_alphaS_In,1)"/>
  <Item Name="RooGaussian::BR_param_mB_Pdf(BR_param_mB,BR_param_mB_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hqq_Pdf(BR_HiggsDecayWidthTHU_hqq,BR_HiggsDecayWidthTHU_hqq_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hvv_Pdf(BR_HiggsDecayWidthTHU_hvv,BR_HiggsDecayWidthTHU_hvv_In,1)"/>

  <!-- Introducing response terms -->
  <!-- H->zz -->
  <Item Name="prod::expected_BR_param_alphaS_zz(RooExponential::expTerm_BR_param_alphaS_zz(BR_param_alphaS, expr::log_kappa_value_BR_param_alphaS_zz('sqrt(log(@0))', kappa_value_BR_param_alphaS_zz)),nominal_BR_param_alphaS_zz[1])"/>
  <Item Name="prod::expected_BR_param_mB_zz(RooExponential::expTerm_BR_param_mB_zz(BR_param_mB, expr::log_kappa_value_BR_param_mB_zz('sqrt(log(@0))', kappa_value_BR_param_mB_zz)),nominal_BR_param_mB_zz[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hqq_zz(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hqq_zz(BR_HiggsDecayWidthTHU_hqq, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hqq_zz('sqrt(log(@0))', kappa_value_BR_HiggsDecayWidthTHU_hqq_zz)),nominal_BR_HiggsDecayWidthTHU_hqq_zz[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hvv_zz(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hvv_zz(BR_HiggsDecayWidthTHU_hvv, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hvv_zz('sqrt(log(@0))', kappa_value_BR_HiggsDecayWidthTHU_hvv_zz)),nominal_BR_HiggsDecayWidthTHU_hvv_zz[1])"/>
  <Item Name="prod:expected_BR_zz_new(expected_BR_param_alphaS_zz,expected_BR_param_mB_zz,expected_BR_HiggsDecayWidthTHU_hqq_zz,expected_BR_HiggsDecayWidthTHU_hvv_zz,mu_BR_zz[1])"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
       	       alpha_ATLAS_BR_VV=zero,
	       alpha_ATLAS_BR_VVConstraint=one,
	       mu_BR_zz_temp=expected_BR_zz_new,
       	       )" />
</Orgnization>

=== phreborn/vbfcp_comb/cfg/lhchcg/ATLAS_param_BR_lumi_zz_toy.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="workspace/lhchcg/myrep/atlas/handler/atlas_h4l_toy_handler.root" OutFile="workspace/lhchcg/myrep/atlas/parambrlumi/atlas_h4l_toy_parambrlumi.root"
	     ModelName="param_BR"
	     POINames="MH,mu_zz">
  <Item Name="zero[0]"/>
  <Item Name="one[1]"/>

  <!-- Introducing kappa values -->
  <!-- H->zz -->
  <Item Name="kappa_value_BR_param_alphaS_zz[1.012]"/>
  <Item Name="kappa_value_BR_param_mB_zz[0.981]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hqq_zz[0.988]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hvv_zz[1.004]"/>

  <Item Name="expr::log_kappa_value_LHC_LUMI_2011('sqrt(log(1+@0*@0))', uncert_LUMI_2011_correlate[0.005])"/>
  <Item Name="expr::log_kappa_value_LHC_LUMI_2012('sqrt(log(1+@0*@0))', uncert_LUMI_2012_correlate[0.011])"/>
  <Item Name="expr::log_kappa_value_ATLAS_LUMI_uncor_2011('sqrt(log(1+@0*@0))', uncert_LUMI_2011_uncorrelate[0.017])"/>
  <Item Name="expr::log_kappa_value_ATLAS_LUMI_uncor_2012('sqrt(log(1+@0*@0))', uncert_LUMI_2012_uncorrelate[0.025])"/>

  <!-- Introducing nuisance parameter names -->
  <Item Name="BR_param_alphaS[0,-5,5]"/>
  <Item Name="BR_param_mB[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hvv[0,-5,5]"/>

  <Item Name="LHC_LUMI_2011[0,-5,5]"/>
  <Item Name="LHC_LUMI_2012[0,-5,5]"/>
  <Item Name="ATLAS_LUMI_uncor_2011[0,-5,5]"/>
  <Item Name="ATLAS_LUMI_uncor_2012[0,-5,5]"/>

  <!-- Introducing global observables -->
  <Item Name="BR_param_alphaS_In[0]"/>
  <Item Name="BR_param_mB_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hvv_In[0]"/>

  <Item Name="LHC_LUMI_2011_In[0]"/>
  <Item Name="LHC_LUMI_2012_In[0]"/>
  <Item Name="ATLAS_LUMI_uncor_2011_In[0]"/>
  <Item Name="ATLAS_LUMI_uncor_2012_In[0]"/>

  <!-- Introducing constraint terms -->
  <Item Name="RooGaussian::BR_param_alphaS_Pdf(BR_param_alphaS,BR_param_alphaS_In,1)"/>
  <Item Name="RooGaussian::BR_param_mB_Pdf(BR_param_mB,BR_param_mB_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hqq_Pdf(BR_HiggsDecayWidthTHU_hqq,BR_HiggsDecayWidthTHU_hqq_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hvv_Pdf(BR_HiggsDecayWidthTHU_hvv,BR_HiggsDecayWidthTHU_hvv_In,1)"/>

  <Item Name="RooGaussian::LHC_LUMI_2011_Pdf(LHC_LUMI_2011,LHC_LUMI_2011_In,1)"/>
  <Item Name="RooGaussian::LHC_LUMI_2012_Pdf(LHC_LUMI_2012,LHC_LUMI_2012_In,1)"/>
  <Item Name="RooGaussian::ATLAS_LUMI_uncor_2011_Pdf(ATLAS_LUMI_uncor_2011,ATLAS_LUMI_uncor_2011_In,1)"/>
  <Item Name="RooGaussian::ATLAS_LUMI_uncor_2012_Pdf(ATLAS_LUMI_uncor_2012,ATLAS_LUMI_uncor_2012_In,1)"/>

  <!-- Introducing response terms -->
  <!-- H->zz -->
  <Item Name="prod::expected_BR_param_alphaS_zz(RooExponential::expTerm_BR_param_alphaS_zz(BR_param_alphaS, expr::log_kappa_value_BR_param_alphaS_zz('log(@0)', kappa_value_BR_param_alphaS_zz)),nominal_BR_param_alphaS_zz[1])"/>
  <Item Name="prod::expected_BR_param_mB_zz(RooExponential::expTerm_BR_param_mB_zz(BR_param_mB, expr::log_kappa_value_BR_param_mB_zz('log(@0)', kappa_value_BR_param_mB_zz)),nominal_BR_param_mB_zz[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hqq_zz(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hqq_zz(BR_HiggsDecayWidthTHU_hqq, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hqq_zz('log(@0)', kappa_value_BR_HiggsDecayWidthTHU_hqq_zz)),nominal_BR_HiggsDecayWidthTHU_hqq_zz[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hvv_zz(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hvv_zz(BR_HiggsDecayWidthTHU_hvv, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hvv_zz('log(@0)', kappa_value_BR_HiggsDecayWidthTHU_hvv_zz)),nominal_BR_HiggsDecayWidthTHU_hvv_zz[1])"/>

  <Item Name="prod::expected_LHC_LUMI_2011(RooExponential::expTerm_LHC_LUMI_2011(LHC_LUMI_2011, log_kappa_value_LHC_LUMI_2011),nominal_LHC_LUMI_2011[1])"/>
  <Item Name="prod::expected_LHC_LUMI_2012(RooExponential::expTerm_LHC_LUMI_2012(LHC_LUMI_2012, log_kappa_value_LHC_LUMI_2012),nominal_LHC_LUMI_2012[1])"/>
  <Item Name="prod::expected_ATLAS_LUMI_uncor_2011(RooExponential::expTerm_ATLAS_LUMI_uncor_2011(ATLAS_LUMI_uncor_2011, log_kappa_value_ATLAS_LUMI_uncor_2011),nominal_ATLAS_LUMI_uncor_2011[1])"/>
  <Item Name="prod::expected_ATLAS_LUMI_uncor_2012(RooExponential::expTerm_ATLAS_LUMI_uncor_2012(ATLAS_LUMI_uncor_2012, log_kappa_value_ATLAS_LUMI_uncor_2012),nominal_ATLAS_LUMI_uncor_2012[1])"/>

  <Item Name="prod:expected_BR_zz_new(expected_BR_param_alphaS_zz,expected_BR_param_mB_zz,expected_BR_HiggsDecayWidthTHU_hqq_zz,expected_BR_HiggsDecayWidthTHU_hvv_zz, expected_LHC_LUMI_2011, expected_LHC_LUMI_2012, expected_ATLAS_LUMI_uncor_2011, expected_ATLAS_LUMI_uncor_2012, mu_BR_ZZ[1])"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
       	       alpha_ATLAS_BR_VV=zero,
	       alpha_ATLAS_LUMI_2011=zero,
	       alpha_ATLAS_LUMI_2012=zero,
	       alpha_ATLAS_BR_VVConstraint=one,
	       alpha_ATLAS_LUMI_2011Constraint=one,
	       alpha_ATLAS_LUMI_2012Constraint=one,
	       mu_BR_ZZ_temp=expected_BR_zz_new,
       	       )" />
</Orgnization>

=== phreborn/vbfcp_comb/cfg/lhchcg/ATLAS_measurement_parametrization_gamgam_asimov.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="workspace/lhchcg/myrep/atlas/decorated/atlas_hgamgam_asimov_decorated.root" OutFile="workspace/lhchcg/myrep/atlas/handler/atlas_hgamgam_asimov_handler.root"
	     ModelName="param_BR"
	     POINames="mH,muF_gg,muV_gg,mu,lambda_mu,lambda_muF_gg,lambda_muV_gg,dmH_gZ,dmH_exp">

  <Item Name="mu[1]"/>
  <Item Name="muF_gg[1,-5,5]"/>
  <Item Name="muV_gg[1,-5,5]"/>

  <!-- <Item Name="mu_BR_gamgam_temp[1]"/> -->

  <!-- <Item Name="prod::RF_comp(RF_gg,mu_BR_gamgam_temp)"/> -->
  <!-- <Item Name="prod::RV_comp(RV_gg,mu_BR_gamgam_temp)"/> -->

  <Item Name="lambda_mu[1]"/>
  <Item Name="lambda_muF_gg[1]"/>
  <Item Name="lambda_muV_gg[1]"/>

  <Item Name="dmH_gZ[0]"/>
  <Item Name="dmH_exp[0]"/>

  <Item Name="mH[125,120,130]"/>  
  <Item Name="prod::RF_comp(muF_gg,mu,lambda_muF_gg,lambda_mu)"/>
  <Item Name="prod::RV_comp(muV_gg,mu,lambda_muV_gg,lambda_mu)"/>

  <Item Name="sum::mH_comp(mH,dmH_gZ,dmH_exp)"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
	       mH=mH_comp,
	       RF=RF_comp,
	       RV=RV_comp
       	       )" />
</Orgnization>

=== phreborn/vbfcp_comb/cfg/lhchcg/cms_v3/CMS_param_BR_gamgam_template.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="#INPUT#" OutFile="#OUTPUT#"
	     ModelName="param_BR"
	     POINames="MH,RF_gg,RV_gg">
  <Item Name="zero[0]"/>
  <Item Name="one[1]"/>

  <!-- Introducing kappa values -->
  <!-- H->gamgam -->
  <Item Name="kappa_value_BR_param_alphaS_gamgam[1.012]"/>
  <Item Name="kappa_value_BR_param_mB_gamgam[0.981]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hqq_gamgam[0.988]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hgg_gamgam[1.010]"/>

  <!-- Introducing nuisance parameter names -->
  <Item Name="BR_param_alphaS[0,-5,5]"/>
  <Item Name="BR_param_mB[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hgg[0,-5,5]"/>

  <!-- Introducing global observables -->
  <Item Name="BR_param_alphaS_In[0]"/>
  <Item Name="BR_param_mB_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hgg_In[0]"/>

  <!-- Introducing constraint terms -->
  <Item Name="RooGaussian::BR_param_alphaS_Pdf(BR_param_alphaS,BR_param_alphaS_In,1)"/>
  <Item Name="RooGaussian::BR_param_mB_Pdf(BR_param_mB,BR_param_mB_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hqq_Pdf(BR_HiggsDecayWidthTHU_hqq,BR_HiggsDecayWidthTHU_hqq_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hgg_Pdf(BR_HiggsDecayWidthTHU_hgg,BR_HiggsDecayWidthTHU_hgg_In,1)"/>

  <!-- Introducing response terms -->
  <!-- H->gamgam -->
  <Item Name="prod::expected_BR_param_alphaS_gamgam(RooExponential::expTerm_BR_param_alphaS_gamgam(BR_param_alphaS, expr::log_kappa_value_BR_param_alphaS_gamgam('sqrt(log(@0))', kappa_value_BR_param_alphaS_gamgam)),nominal_BR_param_alphaS_gamgam[1])"/>
  <Item Name="prod::expected_BR_param_mB_gamgam(RooExponential::expTerm_BR_param_mB_gamgam(BR_param_mB, expr::log_kappa_value_BR_param_mB_gamgam('sqrt(log(@0))', kappa_value_BR_param_mB_gamgam)),nominal_BR_param_mB_gamgam[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hqq_gamgam(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hqq_gamgam(BR_HiggsDecayWidthTHU_hqq, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hqq_gamgam('sqrt(log(@0))', kappa_value_BR_HiggsDecayWidthTHU_hqq_gamgam)),nominal_BR_HiggsDecayWidthTHU_hqq_gamgam[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hgg_gamgam(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hgg_gamgam(BR_HiggsDecayWidthTHU_hgg, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hgg_gamgam('sqrt(log(@0))', kappa_value_BR_HiggsDecayWidthTHU_hgg_gamgam)),nominal_BR_HiggsDecayWidthTHU_hgg_gamgam[1])"/>
  <Item Name="prod:expected_BR_gamgam_new(expected_BR_param_alphaS_gamgam,expected_BR_param_mB_gamgam,expected_BR_HiggsDecayWidthTHU_hqq_gamgam,expected_BR_HiggsDecayWidthTHU_hgg_gamgam,mu_BR_gamgam[1])"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
       	       CMS_hgg_BR=zero,
	       CMS_hgg_BR_Pdf=one,
	       mu_BR_gamgam_temp=expected_BR_gamgam_new,
       	       )" />
</Orgnization>

=== phreborn/vbfcp_comb/cfg/lhchcg/atlas_v1/ATLAS_add_BR_handler_gamgam_template.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="#INPUT#" OutFile="#OUTPUT#"
	     ModelName="param_BR"
	     POINames="MH,RF_gg,RV_gg">
  <Item Name="MH[125,120,130]"/>
  <Item Name="RF_gg[1,0,10]"/>
  <Item Name="RV_gg[1,-10,10]"/>
  <Item Name="mu_BR_gamgam_temp[1]"/>

  <Item Name="prod::RF_comp(RF_gg,mu_BR_gamgam_temp)"/>
  <Item Name="prod::RV_comp(RV_gg,mu_BR_gamgam_temp)"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
	       mH=MH,
	       RF=RF_comp,
	       RV=RV_comp
       	       )" />
</Orgnization>

=== phreborn/vbfcp_comb/cfg/tth/model_plus_NLO.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="workspace/lhchcg/couplings/atlas/ttH/atlas_tthgg_coupling_asimov.root" OutFile="atlas_tthgg_coupling_asimov_param_NLO.root"
	     ModelName="CWCZCbCtaCto"
	     POINames="CT">
  <Item Name="CW[1]"/>
  <Item Name="CZ[1]"/>
  <Item Name="Cb[1]"/>
  <Item Name="Cm[1]"/>
  <Item Name="Cta[1]"/>
  <Item Name="CT[1,-100,100]"/>
  <Item Name="one[1]"/>
  <Item Name="pluone[+1]"/>
  <Item Name="onehalf[0.5]"/>

  <Item Name="expr::Cto('@0*@1', CT, pluone)"/>

  <!-- PRODUCTION -->
  <!-- gluglu->H, 7TeV -->
  <Item Name="expr::C2_GlGlH_7TeV('(@0*@0)*@2  + (@1*@1)*@3 + (@0*@1)*@4', Cto, Cb, sigma_tt_o_sigma_ggH_GlGlH_7TeV[1.0592],sigma_bb_o_sigma_ggH_GlGlH_7TeV[0.0070],sigma_tb_o_sigma_ggH_GlGlH_7TeV[-0.0662])"/>
  <!-- gluglu->H, 8TeV -->
  <Item Name="expr::C2_GlGlH_8TeV('(@0*@0)*@2  + (@1*@1)*@3 + (@0*@1)*@4', Cto, Cb, sigma_tt_o_sigma_ggH_GlGlH_8TeV[1.0580],sigma_bb_o_sigma_ggH_GlGlH_8TeV[0.0070],sigma_tb_o_sigma_ggH_GlGlH_8TeV[-0.0650])"/>
  <!-- VBF->H, 7TeV -->
  <Item Name="expr::C2_VBFH_7TeV('((@0*@0)*@2  + (@1*@1)*@3)', CZ, CW, CZFracVBF_7TeV[0.2548],CWFracVBF_7TeV[0.7452])"/>
  <!-- VBF->H, 8TeV -->
  <Item Name="expr::C2_VBFH_8TeV('((@0*@0)*@2  + (@1*@1)*@3)', CZ, CW, CZFracVBF_8TeV[0.2563],CWFracVBF_8TeV[0.7437])"/>

  <Item Name="expr::CW2('@0*@0',CW)"/>
  <Item Name="expr::CZ2('@0*@0',CZ)"/>
  <Item Name="expr::Cb2('@0*@0',Cb)"/>
  <Item Name="expr::Cm2('@0*@0',Cm)"/>
  <Item Name="expr::Ctau2('@0*@0',Cta)"/>
  <Item Name="expr::Ctop2('@0*@0',Cto)"/>


  <!-- tH xsec and efficiencies -->
  <Item Name="xsec_8TeV_wth_sm[0.00467]"/>
  <Item Name="xsec_8TeV_wth_np[0.0272]"/>
  <Item Name="xsec_8TeV_wth_null[0.00733]"/>
  <Item Name="xsec_8TeV_thjb_sm[0.017152]"/>
  <Item Name="xsec_8TeV_thjb_np[0.19722]"/>
  <Item Name="xsec_8TeV_thjb_null[0.058671]"/>

  <Item Name="eff_8TeV_wth_np[0.135866]"/>
  <Item Name="eff_8TeV_wth_null[0.120133]"/>
  <Item Name="eff_8TeV_wth_sm[0.118878]"/>
  <Item Name="eff_8TeV_thjb_null[0.0633131]"/>
  <Item Name="eff_8TeV_thjb_np[0.0650209]"/>
  <Item Name="eff_8TeV_thjb_sm[0.0615526]"/>

  <Item Name="xsec_7TeV_wth_sm[0.00286]"/>
  <Item Name="xsec_7TeV_wth_np[0.0162]"/>
  <Item Name="xsec_7TeV_wth_null[0.00429]"/>
  <Item Name="xsec_7TeV_thjb_sm[0.0111104]"/>
  <Item Name="xsec_7TeV_thjb_np[0.12876]"/>
  <Item Name="xsec_7TeV_thjb_null[0.0400]"/>

  <Item Name="eff_7TeV_wth_np[0.146362]"/>
  <Item Name="eff_7TeV_wth_null[0.131073]"/>
  <Item Name="eff_7TeV_wth_sm[0.128528]"/>
  <Item Name="eff_7TeV_thjb_null[0.0656412]"/>
  <Item Name="eff_7TeV_thjb_np[0.0669837]"/>
  <Item Name="eff_7TeV_thjb_sm[0.0618059]"/>

  <Item Name="expr::wt_tH_sm('((@0*@0)+(@0*@1))*@2',Cto,CW,onehalf)"/>
  <Item Name="expr::wt_tH_np('((@0*@0)-(@0*@1))*@2',Cto,CW,onehalf)"/>
  <Item Name="expr::wt_tH_null('((@1*@1)-(@0*@0))',Cto,CW)"/>

  <Item Name="expr::C2_7TeV_tHjb('((@0*@3*@6)  + (@1*@4*@7) + (@2*@5*@8))/(@3*@6)', wt_tH_sm, wt_tH_np, wt_tH_null, xsec_7TeV_thjb_sm, xsec_7TeV_thjb_np, xsec_7TeV_thjb_null, eff_7TeV_thjb_sm, eff_7TeV_thjb_np, eff_7TeV_thjb_null)"/>

  <Item Name="expr::C2_7TeV_WtH('((@0*@3*@6)  + (@1*@4*@7) + (@2*@5*@8))/(@3*@6)', wt_tH_sm, wt_tH_np, wt_tH_null, xsec_7TeV_wth_sm, xsec_7TeV_wth_np, xsec_7TeV_wth_null, eff_7TeV_wth_sm, eff_7TeV_wth_np, eff_7TeV_wth_null)"/>

  <Item Name="expr::C2_8TeV_tHjb('((@0*@3*@6)  + (@1*@4*@7) + (@2*@5*@8))/(@3*@6)', wt_tH_sm, wt_tH_np, wt_tH_null, xsec_8TeV_thjb_sm, xsec_8TeV_thjb_np, xsec_8TeV_thjb_null, eff_8TeV_thjb_sm, eff_8TeV_thjb_np, eff_8TeV_thjb_null)"/>

  <Item Name="expr::C2_8TeV_WtH('((@0*@3*@6)  + (@1*@4*@7) + (@2*@5*@8))/(@3*@6)', wt_tH_sm, wt_tH_np, wt_tH_null, xsec_8TeV_wth_sm, xsec_8TeV_wth_np, xsec_8TeV_wth_null, eff_8TeV_wth_sm, eff_8TeV_wth_np, eff_8TeV_wth_null)"/>

  <!-- DECAY -->
  <!-- H->gamgam -->
  <Item Name="expr::C2_HGaGa('(@0*@0)*@4 + (@1*@1)*@5 + (@2*@2)*@6 + (@0*@1)*@7 + (@0*@2)*@8 + (@1*@2)*@9 + (@3*@3)*@10 + (@0*@3)*@11 + (@1*@3)*@12 + (@2*@3)*@13',Cto,Cb,CW,Cta,G_tt_o_G_HGaGa[0.0715],G_bb_o_G_HGaGa[0.0000],G_WW_o_G_HGaGa[1.5887],G_tb_o_G_HGaGa[-0.0018],G_tW_o_G_HGaGa[-0.6740],G_bW_o_G_HGaGa[0.0083],G_ll_o_G_HGaGa[0.0000],G_tl_o_G_HGaGa[-0.0019],G_bl_o_G_HGaGa[0.0000],G_lW_o_G_HGaGa[0.0090])"/>
  <!-- H->Zgam -->
  <Item Name="expr::C2_HZGa('(@0*@0)*@4 + (@1*@1)*@5 + (@2*@2)*@6 + (@0*@1)*@7 + (@0*@2)*@8 + (@1*@2)*@9 + (@3*@3)*@10 + (@0*@3)*@11 + (@1*@3)*@12 + (@2*@3)*@13',Cto,Cb,CW,Cta,G_tt_o_G_HZGa[0.0035],G_bb_o_G_HZGa[0.0000],G_WW_o_G_HZGa[1.1180],G_tb_o_G_HZGa[-0.0002],G_tW_o_G_HZGa[-0.1245],G_bW_o_G_HZGa[0.0032],G_ll_o_G_HZGa[0.0000],G_tl_o_G_HZGa[-0.0000],G_bl_o_G_HZGa[0.0000],G_lW_o_G_HZGa[0.0001])"/>
  <!-- H->gluglu -->
  <Item Name="expr::C2_HGlGl('(@0*@0)*@2  + (@1*@1)*@3 + (@0*@1)*@4', Cto, Cb, G_tt_o_G_gg_HGlGl[1.1114],G_bb_o_G_gg_HGlGl[0.0116],G_tb_o_G_gg_HGlGl[-0.1229])"/>
  <!-- total width -->
  <Item Name="expr::invC2H('1/(@0*@11 + @1*@12 + @2*@13 + @3*@14 + @4*@15 + @5*@16 + @6*@17 + @7*@17 + @8*@16 + @9*@18 + @10*@18)', BR_H_gluglu_SM[0.0850],BR_H_gamgam_SM[0.0023],BR_H_Zgam_SM[0.0016],BR_H_WW_SM[0.2240],BR_H_ZZ_SM[0.0279],BR_H_bb_SM[0.5690],BR_H_tautau_SM[0.0628],BR_H_mumu_SM[0.0002],BR_H_ssbar_SM[0.0004],BR_H_ccbar_SM[0.0264],BR_H_ttbar_SM[0.0000], C2_HGlGl, C2_HGaGa, C2_HZGa, CW2, CZ2, Cb2, Ctau2, Ctop2)"/>

  <!-- PDF -->
  <Item Name="EDIT::NEWPDF(OLDPDF,
	      mu_ggH=one,
	      mu_ggH_7TeV=C2_GlGlH_7TeV,
	      mu_ggH_8TeV=C2_GlGlH_8TeV,
	      mu_VBF=one,
	      mu_VBF_7TeV=C2_VBFH_7TeV,
	      mu_VBF_8TeV=C2_VBFH_7TeV,
	      mu_WH=CW2,
	      mu_ZH=CZ2,
	      mu_ttH=Ctop2,
	      mu_bbH=Cb2,
	      mu_tH=one,
	      mu_tH_7TeV=one,
	      mu_tH_8TeV=one,
	      mu_tHjb=one,
	      mu_tHjb_7TeV=C2_7TeV_tHjb,
	      mu_WtH_7TeV=C2_7TeV_WtH,
	      mu_WtH=one,
	      mu_tHjb_8TeV=C2_8TeV_tHjb,
	      mu_WtH_8TeV=C2_8TeV_WtH,
	      mu_BR_gg=C2_HGaGa,
	      mu=invC2H)"/>
</Orgnization>
