=== phreborn/vbfcp_comb/cfg/lhchcg/Orgnization.dtd
<!ELEMENT Orgnization (Item+)*>
<!ATTLIST Orgnization
        InFile              CDATA            #REQUIRED
        OutFile             CDATA            #REQUIRED
        ModelName           CDATA            #REQUIRED
        POINames            CDATA            #REQUIRED
> 
<!ELEMENT Item (Name)*>
<!ATTLIST Item
        Name              CDATA            #REQUIRED
>

=== phreborn/vbfcp_comb/cfg/lhchcg/ATLAS_param_BR_lumi_gamgam_template.xml
<!DOCTYPE Orgnization  SYSTEM 'Orgnization.dtd'>
<Orgnization InFile="#INPUT#" OutFile="#OUTPUT#"
	     ModelName="param_BR"
	     POINames="MH,RF_gg,RV_gg">
  <Item Name="zero[0]"/>
  <Item Name="one[1]"/>

  <!-- Introducing kappa values -->
  <!-- H->gamgam -->
  <Item Name="kappa_value_BR_param_alphaS_gamgam[1.012]"/>
  <Item Name="kappa_value_BR_param_mB_gamgam[0.981]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hqq_gamgam[0.988]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hgg_gamgam[1.010]"/>

  <Item Name="expr::log_kappa_value_LHC_LUMI_2011('sqrt(log(1+@0*@0))', uncert_LUMI_2011_correlate[0.005])"/>
  <Item Name="expr::log_kappa_value_LHC_LUMI_2012('sqrt(log(1+@0*@0))', uncert_LUMI_2012_correlate[0.011])"/>
  <Item Name="expr::log_kappa_value_ATLAS_LUMI_uncor_2011('sqrt(log(1+@0*@0))', uncert_LUMI_2011_uncorrelate[0.017])"/>
  <Item Name="expr::log_kappa_value_ATLAS_LUMI_uncor_2012('sqrt(log(1+@0*@0))', uncert_LUMI_2012_uncorrelate[0.025])"/>

  <!-- Introducing nuisance parameter names -->
  <Item Name="BR_param_alphaS[0,-5,5]"/>
  <Item Name="BR_param_mB[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hgg[0,-5,5]"/>

  <Item Name="LHC_LUMI_2011[0,-5,5]"/>
  <Item Name="LHC_LUMI_2012[0,-5,5]"/>
  <Item Name="ATLAS_LUMI_uncor_2011[0,-5,5]"/>
  <Item Name="ATLAS_LUMI_uncor_2012[0,-5,5]"/>

  <!-- Introducing global observables -->
  <Item Name="BR_param_alphaS_In[0]"/>
  <Item Name="BR_param_mB_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hqq_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hgg_In[0]"/>

  <Item Name="LHC_LUMI_2011_In[0]"/>
  <Item Name="LHC_LUMI_2012_In[0]"/>
  <Item Name="ATLAS_LUMI_uncor_2011_In[0]"/>
  <Item Name="ATLAS_LUMI_uncor_2012_In[0]"/>

  <!-- Introducing constraint terms -->
  <Item Name="RooGaussian::BR_param_alphaS_Pdf(BR_param_alphaS,BR_param_alphaS_In,1)"/>
  <Item Name="RooGaussian::BR_param_mB_Pdf(BR_param_mB,BR_param_mB_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hqq_Pdf(BR_HiggsDecayWidthTHU_hqq,BR_HiggsDecayWidthTHU_hqq_In,1)"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hgg_Pdf(BR_HiggsDecayWidthTHU_hgg,BR_HiggsDecayWidthTHU_hgg_In,1)"/>

  <Item Name="RooGaussian::LHC_LUMI_2011_Pdf(LHC_LUMI_2011,LHC_LUMI_2011_In,1)"/>
  <Item Name="RooGaussian::LHC_LUMI_2012_Pdf(LHC_LUMI_2012,LHC_LUMI_2012_In,1)"/>
  <Item Name="RooGaussian::ATLAS_LUMI_uncor_2011_Pdf(ATLAS_LUMI_uncor_2011,ATLAS_LUMI_uncor_2011_In,1)"/>
  <Item Name="RooGaussian::ATLAS_LUMI_uncor_2012_Pdf(ATLAS_LUMI_uncor_2012,ATLAS_LUMI_uncor_2012_In,1)"/>

  <!-- Introducing response terms -->
  <!-- H->gamgam -->
  <Item Name="prod::expected_BR_param_alphaS_gamgam(RooExponential::expTerm_BR_param_alphaS_gamgam(BR_param_alphaS, expr::log_kappa_value_BR_param_alphaS_gamgam('log(@0)', kappa_value_BR_param_alphaS_gamgam)),nominal_BR_param_alphaS_gamgam[1])"/>
  <Item Name="prod::expected_BR_param_mB_gamgam(RooExponential::expTerm_BR_param_mB_gamgam(BR_param_mB, expr::log_kappa_value_BR_param_mB_gamgam('log(@0)', kappa_value_BR_param_mB_gamgam)),nominal_BR_param_mB_gamgam[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hqq_gamgam(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hqq_gamgam(BR_HiggsDecayWidthTHU_hqq, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hqq_gamgam('log(@0)', kappa_value_BR_HiggsDecayWidthTHU_hqq_gamgam)),nominal_BR_HiggsDecayWidthTHU_hqq_gamgam[1])"/>
  <Item Name="prod::expected_BR_HiggsDecayWidthTHU_hgg_gamgam(RooExponential::expTerm_BR_HiggsDecayWidthTHU_hgg_gamgam(BR_HiggsDecayWidthTHU_hgg, expr::log_kappa_value_BR_HiggsDecayWidthTHU_hgg_gamgam('log(@0)', kappa_value_BR_HiggsDecayWidthTHU_hgg_gamgam)),nominal_BR_HiggsDecayWidthTHU_hgg_gamgam[1])"/>

  <Item Name="prod::expected_LHC_LUMI_2011(RooExponential::expTerm_LHC_LUMI_2011(LHC_LUMI_2011, log_kappa_value_LHC_LUMI_2011),nominal_LHC_LUMI_2011[1])"/>
  <Item Name="prod::expected_LHC_LUMI_2012(RooExponential::expTerm_LHC_LUMI_2012(LHC_LUMI_2012, log_kappa_value_LHC_LUMI_2012),nominal_LHC_LUMI_2012[1])"/>
  <Item Name="prod::expected_ATLAS_LUMI_uncor_2011(RooExponential::expTerm_ATLAS_LUMI_uncor_2011(ATLAS_LUMI_uncor_2011, log_kappa_value_ATLAS_LUMI_uncor_2011),nominal_ATLAS_LUMI_uncor_2011[1])"/>
  <Item Name="prod::expected_ATLAS_LUMI_uncor_2012(RooExponential::expTerm_ATLAS_LUMI_uncor_2012(ATLAS_LUMI_uncor_2012, log_kappa_value_ATLAS_LUMI_uncor_2012),nominal_ATLAS_LUMI_uncor_2012[1])"/>

  <Item Name="prod:expected_BR_gamgam_new(expected_BR_param_alphaS_gamgam,expected_BR_param_mB_gamgam,expected_BR_HiggsDecayWidthTHU_hqq_gamgam,expected_BR_HiggsDecayWidthTHU_hgg_gamgam, expected_LHC_LUMI_2011, expected_LHC_LUMI_2012, expected_ATLAS_LUMI_uncor_2011, expected_ATLAS_LUMI_uncor_2012, mu_BR_gamgam[1])"/>

  <Item Name= "EDIT::NEWPDF(OLDPDF,
       	       ATLAS_BR=zero,
	       ATLAS_LUMI_2011=zero,
	       ATLAS_LUMI_2012=zero,
	       nui_ATLAS_BR_MoriondCat1_2011=one,
	       nui_ATLAS_LUMI_2011_MoriondCat1_2011=one,
	       nui_ATLAS_LUMI_2012_MoriondCat1_2012=one,
	       mu_BR_gamgam_temp=expected_BR_gamgam_new,
       	       )" />
</Orgnization>
