=== phreborn/vbfcp_comb/dtd/Combination.dtd
<!ELEMENT Combination (Asimov*, Channel+)>
<!ATTLIST Combination
        WorkspaceName      CDATA            #IMPLIED
        ModelConfigName    CDATA            #IMPLIED
        DataName           CDATA            #IMPLIED
        OutputFile         CDATA            #IMPLIED
        POIList            CDATA            #REQUIRED        
> 

<!ELEMENT Asimov EMPTY>
<!ATTLIST Asimov
          Name              CDATA            #REQUIRED
	  Setup             CDATA            #IMPLIED
	  Action            CDATA            #IMPLIED
	  Data              CDATA            #IMPLIED
	  SnapshotAll       CDATA            #IMPLIED
	  SnapshotGlob      CDATA            #IMPLIED
	  SnapshotNuis      CDATA            #IMPLIED
	  SnapshotPOI       CDATA            #IMPLIED
	  >

<!ELEMENT Channel (ChannelPOI, RenameMap*)>
<!ATTLIST Channel
        Name               CDATA            #REQUIRED
        InputFile          CDATA            #REQUIRED                
        WorkspaceName      CDATA            #REQUIRED
        ModelConfigName    CDATA            #REQUIRED
        DataName           CDATA            #REQUIRED
> 

<!ELEMENT ChannelPOI EMPTY>
<!ATTLIST ChannelPOI
        Name               CDATA            #REQUIRED
> 

<!ELEMENT RenameMap (Syst+)>
<!ELEMENT Syst EMPTY>
<!ATTLIST Syst
        OldName               CDATA            #REQUIRED
        NewName               CDATA            #REQUIRED
>

=== phreborn/vbfcp_comb/cfg/lhchcg/cms_v4/CMS_hzz_obs.xml
<!DOCTYPE Combination SYSTEM 'Combination.dtd'>
<Combination>
  <Channel Name="combined" IsCombined="true" Mass="125"> <!-- is combined file -->
    <File Name="combined.root"/>
    <Workspace Name="combWS"/>
    <ModelConfig Name="ModelConfig"/>
    <ModelData Name="combData"/>
    <ModelPOI Name="MH(125~120~130)*MH_gg(1-1), RF_gg[0~5], RV_gg[-5~5], MH(125~120~130)*MH_zz(1-1), mu_zz[0~5]"/>
  </Channel>
  <Channel Name="Cat_CMS_hzz">
    <File Name="workspace/lhchcg/myrep/cms/parambrlumi/hzz.mH.obs_parambrlumi.root"/>
    <Workspace Name="combWS"/>
    <ModelConfig Name="ModelConfig"/>
    <ModelPOI Name="dummy, dummy, dummy, MH, mu_zz"/>
    <ModelData Name="combData"/>
    <RenameMap>
      <!-- Correlated with CMS H->4l -->
      <!-- Luminosity -->
      <Syst OldName = "lumi_7TeV_Pdf(lumi_7TeV, lumi_7TeV_In)" NewName = "CMS_LUMI_2011" />
      <Syst OldName = "lumi_8TeV_Pdf(lumi_8TeV, lumi_8TeV_In)" NewName = "CMS_LUMI_2012" />
      <Syst OldName =                        "LHC_LUMI_2011_Pdf(LHC_LUMI_2011, LHC_LUMI_2011_In)"	NewName =           "LHC_LUMI_2011" />
      <Syst OldName =                        "LHC_LUMI_2012_Pdf(LHC_LUMI_2012, LHC_LUMI_2012_In)"	NewName =           "LHC_LUMI_2012" />
      <Syst OldName = "CMS_LUMI_uncor_2011_Pdf(CMS_LUMI_uncor_2011, CMS_LUMI_uncor_2011_In)"	NewName =   "CMS_LUMI_uncor_2011" />
      <Syst OldName = "CMS_LUMI_uncor_2012_Pdf(CMS_LUMI_uncor_2012, CMS_LUMI_uncor_2012_In)"	NewName =   "CMS_LUMI_uncor_2012" />
      <!-- Theory uncertainties -->
      <Syst OldName = "QCDscale_ggH_Pdf(QCDscale_ggH, QCDscale_ggH_In)" NewName = "QCDscale_Higgs_ggH" />
      <Syst OldName = "QCDscale_qqH_Pdf(QCDscale_qqH, QCDscale_qqH_In)" NewName = "QCDscale_Higgs_qqH" />
      <Syst OldName = "QCDscale_WH_Pdf(QCDscale_WH, QCDscale_WH_In)" NewName = "QCDscale_Higgs_VH" />
      <Syst OldName = "QCDscale_ZH_Pdf(QCDscale_ZH, QCDscale_ZH_In)" NewName = "QCDscale_Higgs_VH" />
      <Syst OldName = "QCDscale_ttH_Pdf(QCDscale_ttH, QCDscale_ttH_In)" NewName = "QCDscale_Higgs_ttH" />
      <Syst OldName = "pdf_gg_Pdf(pdf_gg, pdf_gg_In)" NewName = "pdf_gg" />
      <Syst OldName = "pdf_qqbar_Pdf(pdf_qqbar, pdf_qqbar_In)" NewName = "pdf_qqbar" />
      <Syst OldName =                  "BR_param_alphaS_Pdf(BR_param_alphaS, BR_param_alphaS_In)"	NewName =         "BR_param_alphaS" />
      <Syst OldName =                              "BR_param_mB_Pdf(BR_param_mB, BR_param_mB_In)"	NewName =             "BR_param_mB" />
      <Syst OldName = "BR_HiggsDecayWidthTHU_hqq_Pdf(BR_HiggsDecayWidthTHU_hqq, BR_HiggsDecayWidthTHU_hqq_In)"	NewName = "BR_HiggsDecayWidthTHU_hqq" />
      <Syst OldName = "BR_HiggsDecayWidthTHU_hvv_Pdf(BR_HiggsDecayWidthTHU_hvv, BR_HiggsDecayWidthTHU_hvv_In)"	NewName = "BR_HiggsDecayWidthTHU_hvv" />
      <!-- Lepton efficiency -->
      <Syst OldName = "CMS_eff_e_Pdf(CMS_eff_e, CMS_eff_e_In)" NewName = "CMS_eff_e" />
      <Syst OldName = "CMS_eff_m_Pdf(CMS_eff_m, CMS_eff_m_In)" NewName = "CMS_eff_m" />

      <!-- Decorrelated with CMS H->gamgam: Adding tag CMS_hzz when necessary -->
      <Syst OldName = "BRhiggs_ZZ4l_Pdf(BRhiggs_ZZ4l, BRhiggs_ZZ4l_In)" NewName = "BR_VV" />
      <Syst OldName = "QCDscale_VV_Pdf(QCDscale_VV, QCDscale_VV_In)" NewName = "QCDscale_Bkg_VV_H4l" />
      <Syst OldName = "QCDscale_ggVV_Pdf(QCDscale_ggVV, QCDscale_ggVV_In)" NewName = "QCDscale_Bkg_ggVV" />

      <Syst OldName = "pdf_hzz4l_accept_Pdf(pdf_hzz4l_accept, pdf_hzz4l_accept_In)" NewName = "pdf_Higgs_ACC_H4l_CMS" />

      <Syst OldName = "CMS_hzz2e2mu_Zjets_Pdf(CMS_hzz2e2mu_Zjets, CMS_hzz2e2mu_Zjets_In)" NewName = "CMS_hzz2e2mu_Zjets" />
      <Syst OldName = "CMS_hzz4e_Zjets_Pdf(CMS_hzz4e_Zjets, CMS_hzz4e_Zjets_In)" NewName = "CMS_hzz4e_Zjets" />
      <Syst OldName = "CMS_hzz4mu_Zjets_Pdf(CMS_hzz4mu_Zjets, CMS_hzz4mu_Zjets_In)" NewName = "CMS_hzz4mu_Zjets" />
      <Syst OldName = "CMS_zz4l_bkgMELA_Pdf(CMS_zz4l_bkgMELA, CMS_zz4l_bkgMELA_In)" NewName = "CMS_hzz_bkgMELA" />

      <Syst OldName = "CMS_zz4l_n_sig_4e_7TeV_Pdf(CMS_zz4l_n_sig_4e_7TeV, CMS_zz4l_n_sig_4e_7TeV_In)" NewName = "CMS_hzz_n_sig_4e_7TeV" />
      <Syst OldName = "CMS_zz4l_n_sig_4mu_7TeV_Pdf(CMS_zz4l_n_sig_4mu_7TeV, CMS_zz4l_n_sig_4mu_7TeV_In)" NewName = "CMS_hzz_n_sig_4mu_7TeV" />
      <Syst OldName = "CMS_zz4l_n_sig_4mu_8TeV_Pdf(CMS_zz4l_n_sig_4mu_8TeV, CMS_zz4l_n_sig_4mu_8TeV_In)" NewName = "CMS_hzz_n_sig_4mu_8TeV" />
      <Syst OldName = "CMS_zz4l_n_sig_4e_8TeV_Pdf(CMS_zz4l_n_sig_4e_8TeV, CMS_zz4l_n_sig_4e_8TeV_In)" NewName = "CMS_hzz_n_sig_4e_8TeV" />
      <Syst OldName = "CMS_zz4l_n_sig_2e2mu_7TeV_Pdf(CMS_zz4l_n_sig_2e2mu_7TeV, CMS_zz4l_n_sig_2e2mu_7TeV_In)" NewName = "CMS_hzz_n_sig_2e2mu_7TeV" />
      <Syst OldName = "CMS_zz4l_n_sig_2e2mu_8TeV_Pdf(CMS_zz4l_n_sig_2e2mu_8TeV, CMS_zz4l_n_sig_2e2mu_8TeV_In)" NewName = "CMS_hzz_n_sig_2e2mu_8TeV" />

      <Syst OldName = "CMS_zz4l_mean_m_sig_Pdf(CMS_zz4l_mean_m_sig, CMS_zz4l_mean_m_sig_In)" NewName = "CMS_hzz_mean_m_sig" />
      <Syst OldName = "CMS_zz4l_sigma_m_sig_Pdf(CMS_zz4l_sigma_m_sig, CMS_zz4l_sigma_m_sig_In)" NewName = "CMS_hzz_sigma_m_sig" />
      <Syst OldName = "CMS_zz4l_mean_e_sig_Pdf(CMS_zz4l_mean_e_sig, CMS_zz4l_mean_e_sig_In)" NewName = "CMS_hzz_mean_e_sig" />
      <Syst OldName = "CMS_zz4l_sigma_e_sig_Pdf(CMS_zz4l_sigma_e_sig, CMS_zz4l_sigma_e_sig_In)" NewName = "CMS_hzz_sigma_e_sig" />

      <Syst OldName= "CMS_channel"   NewName= "Cat_CMS_hzz"/>
    </RenameMap>
  </Channel>
</Combination>

=== phreborn/vbfcp_comb/cfg/lhchcg/LHC_hzz_postfit.xml
<!DOCTYPE Combination  SYSTEM 'Combination.dtd'>
<Combination>
  <Channel Name="combined" IsCombined="true" Mass="125.5">
    <File Name="./combined.root"/>
    <Workspace Name="combWS"/>
    <ModelConfig  Name="ModelConfig"/>
    <ModelData Name="combData"/>
    <ModelPOI Name="mH[120~130], dmH_gZ[0~0], dmH_exp[0~0], 
		    mu[1~1], muF_gg[0~5], muV_gg[-5~5], mu_ZZ[0~5],
		    lambda_mu[1~1], lambda_muF_gg[1~1], lambda_muV_gg[1~1],lambda_mu_ZZ[1~1]"/>

  </Channel>
  <Channel Name="Cat_ATLAS_hzz">
    <File Name="workspace/lhchcg/myrep/atlas/decorated/atlas_h4l_postfit_decorated.root"/>
    <Workspace Name="combWS"/>
    <ModelConfig Name="ModelConfig"/>
    <ModelPOI Name="mH, dummy, dmH_exp,
		    mu, dummy, dummy, mu_ZZ,
		    lambda_mu, dummy, dummy, lambda_mu_ZZ"/>
    <ModelData Name="combData"/>
    <RenameMap>
<Syst OldName =                  "ATLAS_lumi_2011_Pdf(ATLAS_lumi_2011, ATLAS_lumi_2011_In)"	NewName =         "ATLAS_lumi_2011" />
<Syst OldName =                                    "lumi_2011_Pdf(lumi_2011, lumi_2011_In)"	NewName =               "lumi_2011" />
<Syst OldName =                  "ATLAS_lumi_2012_Pdf(ATLAS_lumi_2012, ATLAS_lumi_2012_In)"	NewName =         "ATLAS_lumi_2012" />
<Syst OldName =                                    "lumi_2012_Pdf(lumi_2012, lumi_2012_In)"	NewName =               "lumi_2012" />

<Syst OldName =                           "param_alphaS_Pdf(param_alphaS, param_alphaS_In)"	NewName =            "param_alphaS" />
<Syst OldName =                                       "param_mB_Pdf(param_mB, param_mB_In)"	NewName =                "param_mB" />
<Syst OldName = "HiggsDecayWidthTHU_hvv_Pdf(HiggsDecayWidthTHU_hvv, HiggsDecayWidthTHU_hvv_In)"	NewName =  "HiggsDecayWidthTHU_hvv" />
<Syst OldName = "HiggsDecayWidthTHU_hqq_Pdf(HiggsDecayWidthTHU_hqq, HiggsDecayWidthTHU_hqq_In)"	NewName =  "HiggsDecayWidthTHU_hqq" />
<Syst OldName =                                             "pdf_gg_Pdf(pdf_gg, pdf_gg_In)"	NewName =                  "pdf_gg" />
<Syst OldName =                                    "pdf_qqbar_Pdf(pdf_qqbar, pdf_qqbar_In)"	NewName =               "pdf_qqbar" />
<Syst OldName =                           "QCDscale_ggH_Pdf(QCDscale_ggH, QCDscale_ggH_In)"	NewName =            "QCDscale_ggH" />
<Syst OldName =                              "QCDscale_VV_Pdf(QCDscale_VV, QCDscale_VV_In)"	NewName =             "QCDscale_VV" />

<Syst OldName =                        "ATLAS_EM_ES_Z_Pdf(ATLAS_EM_ES_Z, ATLAS_EM_ES_Z_In)"	NewName =           "ATLAS_EM_ES_Z" />

<Syst OldName =                              "ATLAS_MU_MS_Pdf(ATLAS_MU_MS, ATLAS_MU_MS_In)"	NewName =             "ATLAS_MU_MS" />
<Syst OldName =                           "ATLAS_MU_EFF_Pdf(ATLAS_MU_EFF, ATLAS_MU_EFF_In)"	NewName =            "ATLAS_MU_EFF" />
<Syst OldName = "ATLAS_norm_SF_H4l_Zbb_llmumu_2011_Pdf(ATLAS_norm_SF_H4l_Zbb_llmumu_2011, ATLAS_norm_SF_H4l_Zbb_llmumu_2011_In)"	NewName = "ATLAS_norm_SF_H4l_Zbb_llmumu_2011" />
<Syst OldName = "ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2011_Pdf(ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2011, ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2011_In)"	NewName = "ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2011" />
<Syst OldName = "ATLAS_norm_SF_H4l_Z_llee_2011_Pdf(ATLAS_norm_SF_H4l_Z_llee_2011, ATLAS_norm_SF_H4l_Z_llee_2011_In)"	NewName = "ATLAS_norm_SF_H4l_Z_llee_2011" />
<Syst OldName = "ATLAS_norm_SF_H4l_Zbb_llmumu_2012_Pdf(ATLAS_norm_SF_H4l_Zbb_llmumu_2012, ATLAS_norm_SF_H4l_Zbb_llmumu_2012_In)"	NewName = "ATLAS_norm_SF_H4l_Zbb_llmumu_2012" />
<Syst OldName =   "ATLAS_EL_2012_ID_low_Pdf(ATLAS_EL_2012_ID_low, ATLAS_EL_2012_ID_low_In)"	NewName =    "ATLAS_EL_2012_ID_low" />
<Syst OldName = "ATLAS_EL_2012_IDST_high_Pdf(ATLAS_EL_2012_IDST_high, ATLAS_EL_2012_IDST_high_In)"	NewName = "ATLAS_EL_2012_IDST_high" />
<Syst OldName = "ATLAS_EL_2012_REC_low_Pdf(ATLAS_EL_2012_REC_low, ATLAS_EL_2012_REC_low_In)"	NewName =   "ATLAS_EL_2012_REC_low" />
<Syst OldName = "ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2012_Pdf(ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2012, ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2012_In)"	NewName = "ATLAS_shape_SF_H4l_EL_EFF_ISOIP_2012" />
<Syst OldName = "ATLAS_norm_SF_H4l_Z_llee_2012_Pdf(ATLAS_norm_SF_H4l_Z_llee_2012, ATLAS_norm_SF_H4l_Z_llee_2012_In)"	NewName = "ATLAS_norm_SF_H4l_Z_llee_2012" />

<Syst OldName=       "channelCat" 		NewName=      "Cat_ATLAS_hzz"/>
    </RenameMap>
  </Channel>
  <Channel Name="Cat_CMS_hzz">
    <File Name="workspace/lhchcg/myrep/cms/decorated/hzz.mH.postfit.asimov_decorated.root"/>
    <Workspace Name="combWS"/>
    <ModelConfig Name="ModelConfig"/>
    <ModelPOI Name="MH, dummy, dummy,
		    mu, dummy, dummy, mu_ZZ,
		    dummy, dummy, dummy, dummy"/>
    <ModelData Name="combData"/>
    <RenameMap>
<Syst OldName =                                    "lumi_2011_Pdf(lumi_2011, lumi_2011_In)"	NewName =               "lumi_2011" />
<Syst OldName =                        "CMS_lumi_2011_Pdf(CMS_lumi_2011, CMS_lumi_2011_In)"	NewName =           "CMS_lumi_2011" />
<Syst OldName =                                    "lumi_2012_Pdf(lumi_2012, lumi_2012_In)"	NewName =               "lumi_2012" />
<Syst OldName =                        "CMS_lumi_2012_Pdf(CMS_lumi_2012, CMS_lumi_2012_In)"	NewName =           "CMS_lumi_2012" />

<Syst OldName =                           "param_alphaS_Pdf(param_alphaS, param_alphaS_In)"	NewName =            "param_alphaS" />
<Syst OldName =                                       "param_mB_Pdf(param_mB, param_mB_In)"	NewName =                "param_mB" />
<Syst OldName = "HiggsDecayWidthTHU_hqq_Pdf(HiggsDecayWidthTHU_hqq, HiggsDecayWidthTHU_hqq_In)"	NewName =  "HiggsDecayWidthTHU_hqq" />
<Syst OldName = "HiggsDecayWidthTHU_hvv_Pdf(HiggsDecayWidthTHU_hvv, HiggsDecayWidthTHU_hvv_In)"	NewName =  "HiggsDecayWidthTHU_hvv" />
<Syst OldName =                                             "pdf_gg_Pdf(pdf_gg, pdf_gg_In)"	NewName =                  "pdf_gg" />
<Syst OldName =                                    "pdf_qqbar_Pdf(pdf_qqbar, pdf_qqbar_In)"	NewName =               "pdf_qqbar" />
<Syst OldName =               "pdf_hzz4l_accept_Pdf(pdf_hzz4l_accept, pdf_hzz4l_accept_In)"	NewName =        "pdf_hzz4l_accept" />
<Syst OldName =                           "QCDscale_ggH_Pdf(QCDscale_ggH, QCDscale_ggH_In)"	NewName =            "QCDscale_ggH" />
<Syst OldName =                           "QCDscale_qqH_Pdf(QCDscale_qqH, QCDscale_qqH_In)"	NewName =            "QCDscale_qqH" />
<Syst OldName =                              "QCDscale_VH_Pdf(QCDscale_VH, QCDscale_VH_In)"	NewName =             "QCDscale_VH" />
<Syst OldName =                           "QCDscale_ttH_Pdf(QCDscale_ttH, QCDscale_ttH_In)"	NewName =            "QCDscale_ttH" />
<Syst OldName =                              "QCDscale_VV_Pdf(QCDscale_VV, QCDscale_VV_In)"	NewName =             "QCDscale_VV" />
<Syst OldName =                        "QCDscale_ggVV_Pdf(QCDscale_ggVV, QCDscale_ggVV_In)"	NewName =           "QCDscale_ggVV" />

<Syst OldName =                                    "CMS_eff_e_Pdf(CMS_eff_e, CMS_eff_e_In)"	NewName =               "CMS_eff_e" />
<Syst OldName =                                    "CMS_eff_m_Pdf(CMS_eff_m, CMS_eff_m_In)"	NewName =               "CMS_eff_m" />
<Syst OldName =         "CMS_hzz2e2mu_Zjets_Pdf(CMS_hzz2e2mu_Zjets, CMS_hzz2e2mu_Zjets_In)"	NewName =      "CMS_hzz2e2mu_Zjets" />
<Syst OldName =                  "CMS_hzz4e_Zjets_Pdf(CMS_hzz4e_Zjets, CMS_hzz4e_Zjets_In)"	NewName =         "CMS_hzz4e_Zjets" />
<Syst OldName =               "CMS_hzz4mu_Zjets_Pdf(CMS_hzz4mu_Zjets, CMS_hzz4mu_Zjets_In)"	NewName =        "CMS_hzz4mu_Zjets" />

<Syst OldName = "CMS_zz4l_n_sig_4e_7TeV_Pdf(CMS_zz4l_n_sig_4e_7TeV, CMS_zz4l_n_sig_4e_7TeV_In)"	NewName =  "CMS_zz4l_n_sig_4e_7TeV" />
<Syst OldName = "CMS_zz4l_n_sig_4mu_7TeV_Pdf(CMS_zz4l_n_sig_4mu_7TeV, CMS_zz4l_n_sig_4mu_7TeV_In)"	NewName = "CMS_zz4l_n_sig_4mu_7TeV" />
<Syst OldName = "CMS_zz4l_n_sig_4mu_8TeV_Pdf(CMS_zz4l_n_sig_4mu_8TeV, CMS_zz4l_n_sig_4mu_8TeV_In)"	NewName = "CMS_zz4l_n_sig_4mu_8TeV" />
<Syst OldName =      "CMS_zz4l_mean_m_sig_Pdf(CMS_zz4l_mean_m_sig, CMS_zz4l_mean_m_sig_In)"	NewName =     "CMS_zz4l_mean_m_sig" />
<Syst OldName =               "CMS_zz4l_bkgMELA_Pdf(CMS_zz4l_bkgMELA, CMS_zz4l_bkgMELA_In)"	NewName =        "CMS_zz4l_bkgMELA" />
<Syst OldName =      "CMS_zz4l_mean_e_sig_Pdf(CMS_zz4l_mean_e_sig, CMS_zz4l_mean_e_sig_In)"	NewName =     "CMS_zz4l_mean_e_sig" />
<Syst OldName =   "CMS_zz4l_sigma_m_sig_Pdf(CMS_zz4l_sigma_m_sig, CMS_zz4l_sigma_m_sig_In)"	NewName =    "CMS_zz4l_sigma_m_sig" />
<Syst OldName = "CMS_zz4l_n_sig_2e2mu_7TeV_Pdf(CMS_zz4l_n_sig_2e2mu_7TeV, CMS_zz4l_n_sig_2e2mu_7TeV_In)"	NewName = "CMS_zz4l_n_sig_2e2mu_7TeV" />
<Syst OldName =   "CMS_zz4l_sigma_e_sig_Pdf(CMS_zz4l_sigma_e_sig, CMS_zz4l_sigma_e_sig_In)"	NewName =    "CMS_zz4l_sigma_e_sig" />
<Syst OldName = "CMS_zz4l_n_sig_4e_8TeV_Pdf(CMS_zz4l_n_sig_4e_8TeV, CMS_zz4l_n_sig_4e_8TeV_In)"	NewName =  "CMS_zz4l_n_sig_4e_8TeV" />
<Syst OldName = "CMS_zz4l_n_sig_2e2mu_8TeV_Pdf(CMS_zz4l_n_sig_2e2mu_8TeV, CMS_zz4l_n_sig_2e2mu_8TeV_In)"	NewName = "CMS_zz4l_n_sig_2e2mu_8TeV" />
<Syst OldName= "CMS_channel"   NewName= "Cat_CMS_hzz"/>
    </RenameMap>
  </Channel>
</Combination>

=== phreborn/vbfcp_comb/cfg/lhchcg/cms_v1/cms_hgamgam_v0.xml
<!DOCTYPE Combination  SYSTEM 'Combination.dtd'>
<Combination>
  <Channel Name="combined" IsCombined="true" Mass="125.5"> <!-- is combined file -->
    <File Name="/xdata10/hji/autumn/eps0/output/hsg12345/125.5_hsg12345.xml_125.5.root"/>
    <Workspace Name="combWS"/>
    <ModelConfig  Name="ModelConfig"/>
    <ModelData Name="combData"/>
    <ModelPOI Name="m_H[120~130], RF[0~5], RV[-5~5]"/>
  </Channel>
  <Channel Name="Cat_CMS_hgg">
    <File Name="workspace/lhchcg/myrep/cms/decorated/hgg.mH.prefit.asimov_decorated.root"/>
    <Workspace Name="combWS"/>
    <ModelConfig Name="ModelConfig"/>
    <ModelPOI Name="MH, RF, RV"/>
    <ModelData Name="combData"/>
    <RenameMap>
      <Syst OldName =               "CMS_eff_b"	NewName =               "CMS_eff_b" />
      <Syst OldName =               "CMS_eff_e"	NewName =               "CMS_eff_e" />
      <Syst OldName =               "CMS_eff_j"	NewName =               "CMS_eff_j" />
      <Syst OldName =               "CMS_eff_m"	NewName =               "CMS_eff_m" />
      <Syst OldName =              "CMS_hgg_BR"	NewName =              "BR_gamgam" />
      <Syst OldName =        "CMS_hgg_n_id_eff"	NewName =        "CMS_hgg_n_id_eff" />
      <Syst OldName =        "CMS_hgg_n_id_mva"	NewName =        "CMS_hgg_n_id_mva" />
      <Syst OldName =         "CMS_hgg_n_pdf_1"	NewName =         "CMS_hgg_n_pdf_1" />
      <Syst OldName =        "CMS_hgg_n_pdf_10"	NewName =        "CMS_hgg_n_pdf_10" />
      <Syst OldName =        "CMS_hgg_n_pdf_11"	NewName =        "CMS_hgg_n_pdf_11" />
      <Syst OldName =        "CMS_hgg_n_pdf_12"	NewName =        "CMS_hgg_n_pdf_12" />
      <Syst OldName =        "CMS_hgg_n_pdf_13"	NewName =        "CMS_hgg_n_pdf_13" />
      <Syst OldName =        "CMS_hgg_n_pdf_14"	NewName =        "CMS_hgg_n_pdf_14" />
      <Syst OldName =        "CMS_hgg_n_pdf_15"	NewName =        "CMS_hgg_n_pdf_15" />
      <Syst OldName =        "CMS_hgg_n_pdf_16"	NewName =        "CMS_hgg_n_pdf_16" />
      <Syst OldName =        "CMS_hgg_n_pdf_17"	NewName =        "CMS_hgg_n_pdf_17" />
      <Syst OldName =        "CMS_hgg_n_pdf_18"	NewName =        "CMS_hgg_n_pdf_18" />
      <Syst OldName =        "CMS_hgg_n_pdf_19"	NewName =        "CMS_hgg_n_pdf_19" />
      <Syst OldName =         "CMS_hgg_n_pdf_2"	NewName =         "CMS_hgg_n_pdf_2" />
      <Syst OldName =        "CMS_hgg_n_pdf_20"	NewName =        "CMS_hgg_n_pdf_20" />
      <Syst OldName =        "CMS_hgg_n_pdf_21"	NewName =        "CMS_hgg_n_pdf_21" />
      <Syst OldName =        "CMS_hgg_n_pdf_22"	NewName =        "CMS_hgg_n_pdf_22" />
      <Syst OldName =        "CMS_hgg_n_pdf_23"	NewName =        "CMS_hgg_n_pdf_23" />
      <Syst OldName =        "CMS_hgg_n_pdf_24"	NewName =        "CMS_hgg_n_pdf_24" />
      <Syst OldName =        "CMS_hgg_n_pdf_25"	NewName =        "CMS_hgg_n_pdf_25" />
      <Syst OldName =        "CMS_hgg_n_pdf_26"	NewName =        "CMS_hgg_n_pdf_26" />
      <Syst OldName =         "CMS_hgg_n_pdf_3"	NewName =         "CMS_hgg_n_pdf_3" />
      <Syst OldName =         "CMS_hgg_n_pdf_4"	NewName =         "CMS_hgg_n_pdf_4" />
      <Syst OldName =         "CMS_hgg_n_pdf_5"	NewName =         "CMS_hgg_n_pdf_5" />
      <Syst OldName =         "CMS_hgg_n_pdf_6"	NewName =         "CMS_hgg_n_pdf_6" />
      <Syst OldName =         "CMS_hgg_n_pdf_7"	NewName =         "CMS_hgg_n_pdf_7" />
      <Syst OldName =         "CMS_hgg_n_pdf_8"	NewName =         "CMS_hgg_n_pdf_8" />
      <Syst OldName =         "CMS_hgg_n_pdf_9"	NewName =         "CMS_hgg_n_pdf_9" />
      <Syst OldName =        "CMS_hgg_n_sc_ggH"	NewName =        "CMS_hgg_n_sc_ggH" />
      <Syst OldName =        "CMS_hgg_n_sc_qqH"	NewName =        "CMS_hgg_n_sc_qqH" />
      <Syst OldName =        "CMS_hgg_n_sigmae"	NewName =        "CMS_hgg_n_sigmae" />
      <Syst OldName =      "CMS_hgg_n_trig_eff"	NewName =      "CMS_hgg_n_trig_eff" />
      <Syst OldName = "CMS_hgg_tth_gluon_splitting"	NewName = "CMS_hgg_tth_gluon_splitting" />
      <Syst OldName = "CMS_hgg_tth_mc_low_stat"	NewName = "CMS_hgg_tth_mc_low_stat" />
      <Syst OldName = "CMS_hgg_tth_parton_shower"	NewName = "CMS_hgg_tth_parton_shower" />
      <Syst OldName =             "CMS_scale_j"	NewName =             "CMS_scale_j" />
      <Syst OldName =  "CMS_scale_j_migration1"	NewName =  "CMS_scale_j_migration1" />
      <Syst OldName =  "CMS_scale_j_migration2"	NewName =  "CMS_scale_j_migration2" />
      <Syst OldName =           "CMS_scale_met"	NewName =           "CMS_scale_met" />
      <Syst OldName =             "QCDscale_VH"	NewName =             "QCDscale_Higgs_VH" />
      <Syst OldName =          "QCDscale_gg2in"	NewName =          "QCDscale_Higgs_gg2in_CMS" />
      <Syst OldName = "QCDscale_gg2in_migration1"	NewName = "QCDscale_Higgs_gg2in_migration1_CMS" />
      <Syst OldName = "QCDscale_gg2in_migration2"	NewName = "QCDscale_Higgs_gg2in_migration2_CMS" />
      <Syst OldName =            "QCDscale_ggH"	NewName =            "QCDscale_Higgs_ggH" />
      <Syst OldName =            "QCDscale_qqH"	NewName =            "QCDscale_Higgs_qqH" />
      <Syst OldName =            "QCDscale_ttH"	NewName =            "QCDscale_Higgs_ttH" />
      <Syst OldName =                    "UEPS"	NewName =                "CMS_UEPS" />
      <Syst OldName =         "UEPS_migration1"	NewName =         "CMS_UEPS_migration1" />
      <Syst OldName =         "UEPS_migration2"	NewName =         "CMS_UEPS_migration2" />
      <Syst OldName =               "lumi_7TeV"	NewName =               "CMS_LUMI_2011" />
      <Syst OldName =               "lumi_8TeV"	NewName =               "CMS_LUMI_2012" />
      <Syst OldName =                  "pdf_gg"	NewName =               "pdf_Higgs_ggH" />
      <Syst OldName =               "pdf_qqbar"	NewName =               "pdf_Higgs_qqH" />
      <Syst OldName = "CMS_hgg_nuisance_EElowR9_7TeVsmear"	NewName = "CMS_hgg_nuisance_EElowR9_7TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_eigen1_EElowR9_scale"	NewName = "CMS_hgg_nuisance_eigen1_EElowR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_NonLinearity_7TeVscale"	NewName = "CMS_hgg_nuisance_NonLinearity_7TeVscale" />
      <Syst OldName = "CMS_hgg_nuisance_EBlowR9Phi_8TeVsmear"	NewName = "CMS_hgg_nuisance_EBlowR9Phi_8TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_Geant4_scale"	        NewName = "CMS_hgg_nuisance_Geant4_scale" />
      <Syst OldName = "CMS_hgg_nuisance_EBhighR9Phi_7TeVsmear"	NewName = "CMS_hgg_nuisance_EBhighR9Phi_7TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_MaterialEBOuterEE_scale"	NewName = "CMS_hgg_nuisance_MaterialEBOuterEE_scale" />
      <Syst OldName = "CMS_hgg_nuisance_Absolute_scale"	NewName = "CMS_hgg_nuisance_Absolute_scale" />
      <Syst OldName = "CMS_hgg_nuisance_EElowR9_8TeVsmear"	NewName = "CMS_hgg_nuisance_EElowR9_8TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_EEhighR9_8TeVsmear"	NewName = "CMS_hgg_nuisance_EEhighR9_8TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_eigen1_EEhighR9_scale"	NewName = "CMS_hgg_nuisance_eigen1_EEhighR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_deltafracright"	NewName = "CMS_hgg_nuisance_deltafracright" />
      <Syst OldName = "CMS_hgg_nuisance_EBhighR9_8TeVsmear"	NewName = "CMS_hgg_nuisance_EBhighR9_8TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_EBlowR9Phi_7TeVsmear"	NewName = "CMS_hgg_nuisance_EBlowR9Phi_7TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_LightColl_scale"	NewName = "CMS_hgg_nuisance_LightColl_scale" />
      <Syst OldName = "CMS_hgg_nuisance_EBhighR9Phi_8TeVsmear"	NewName = "CMS_hgg_nuisance_EBhighR9Phi_8TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_eigen1_EBhighR9_scale"	NewName = "CMS_hgg_nuisance_eigen1_EBhighR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_eigen2_EBhighR9_scale"	NewName = "CMS_hgg_nuisance_eigen2_EBhighR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_EBlowR9_7TeVsmear"	NewName = "CMS_hgg_nuisance_EBlowR9_7TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_EBhighR9_7TeVsmear"	NewName = "CMS_hgg_nuisance_EBhighR9_7TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_eigen2_EElowR9_scale"	NewName = "CMS_hgg_nuisance_eigen2_EElowR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_eigen2_EBlowR9_scale"	NewName = "CMS_hgg_nuisance_eigen2_EBlowR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_EEhighR9_7TeVsmear"	NewName = "CMS_hgg_nuisance_EEhighR9_7TeVsmear" />
      <Syst OldName = "CMS_hgg_nuisance_MaterialEBCentral_scale"	NewName = "CMS_hgg_nuisance_MaterialEBCentral_scale" />
      <Syst OldName = "CMS_hgg_nuisance_eigen1_EBlowR9_scale"	NewName = "CMS_hgg_nuisance_eigen1_EBlowR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_NonLinearity_scale"	NewName = "CMS_hgg_nuisance_NonLinearity_scale" />
      <Syst OldName = "CMS_hgg_nuisance_eigen2_EEhighR9_scale"	NewName = "CMS_hgg_nuisance_eigen2_EEhighR9_scale" />
      <Syst OldName = "CMS_hgg_nuisance_EBlowR9_8TeVsmear"	NewName = "CMS_hgg_nuisance_EBlowR9_8TeVsmear" />

      <Syst OldName=       "CMS_channel" 		NewName=      "Cat_CMS_hgg"/>
    </RenameMap>
  </Channel>
</Combination>
