=== phreborn/vbfcp_comb/cfg/tth/Organization.dtd
<!ELEMENT Organization (Item+)*>
<!ATTLIST Organization
        InFile              CDATA            #REQUIRED
        OutFile             CDATA            #REQUIRED
        ModelName           CDATA            #REQUIRED
        POINames            CDATA            #REQUIRED
> 
<!ELEMENT Item (Name)*>
<!ATTLIST Item
        Name              CDATA            #REQUIRED
>

=== phreborn/vbfcp_comb/cfg/vv/lvqq_jes.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization InFile="#INPUT#" OutFile="#OUTPUT#"
	     ModelName="llqq"
	     POINames="mu">
  <Item Name="one[1]"/>

  <Item Name="ATLAS_Jet_Scale1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_Jet_Scale1[0]"/>
  <Item Name="RooGaussian::ATLAS_Jet_Scale1Constraint(ATLAS_Jet_Scale1, nom_ATLAS_Jet_Scale1, 1)"/>

  <Item Name="ATLAS_LargeR_Scale1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_LargeR_Scale1[0]"/>
  <Item Name="RooGaussian::ATLAS_LargeR_Scale1Constraint(ATLAS_LargeR_Scale1, nom_ATLAS_LargeR_Scale1, 1)"/>

  <Item Name="ATLAS_LargeR_Res1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_LargeR_Res1[0]"/>
  <Item Name="RooGaussian::ATLAS_LargeR_Res1Constraint(ATLAS_LargeR_Res1, nom_ATLAS_LargeR_Res1, 1)"/>

  <!-- PDF -->
  <Item Name="EDIT::NEWPDF(OLDPDF,
	      alpha_JET_GroupedNP_2Constraint=one,
	      alpha_JET_WZ_Run1_pTConstraint=one,
	      alpha_JET_WZ_Run1_massConstraint=one,
	      alpha_JET_WZ_Run1_D2Constraint=one,
	      alpha_FATJET_JERConstraint=one,
	      alpha_FATJET_JMRConstraint=one,
	      alpha_JET_GroupedNP_2=ATLAS_Jet_Scale1,
	      alpha_JET_WZ_Run1_pT=ATLAS_Jet_Scale1,
	      alpha_JET_WZ_Run1_mass=ATLAS_LargeR_Scale1,
	      alpha_JET_WZ_Run1_D2=ATLAS_LargeR_Scale1,
	      alpha_FATJET_JER=ATLAS_LargeR_Res1,
	      alpha_FATJET_JMR=ATLAS_LargeR_Res1,
	      )"/>
</Organization>

=== phreborn/vbfcp_comb/modVBFCP/modTauXml/example.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization InFile="inWS/tautau/m00/125_lumi_split.root" OutFile="inWS/tautau/m00/125_lumi_split_mod.root"
	      ModelName="Htautau"
              POINames="ATLAS_epsilon_rejected,ATLAS_epsilon,
              mu_Htau,mu_BR_tautau_mod,mu_BR_WW_mod,
              mu_VBF,mu_otherH"
              WorkspaceName="combined"
              DataName="obsData">

  <Item Name="zero[0]"/>
  <Item Name="one[1]"/>

  <Item Name="mu_Htau[1]"/>
  <Item Name="mu_BR_tautau_mod[1]"/>
  <Item Name="mu_BR_WW_mod[1]"/>
  <Item Name="mu_VBF[1]"/>
  <Item Name="mu_otherH[1]"/>

  <Item Name="kappa_value_BR_param_alphaS_WW[1.0063]"/>
  <Item Name="kappa_value_BR_param_mB_WW[0.9901]"/>
  <Item Name="kappa_value_BR_param_mC_WW[0.9985]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hbb_WW[0.9971]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hgg_WW[0.9974]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hVV_WW[1.0038]"/>

  <Item Name="kappa_value_BR_param_alphaS_tautau[1.0063]"/>
  <Item Name="kappa_value_BR_param_mB_tautau[0.9901]"/>
  <Item Name="kappa_value_BR_param_mC_tautau[0.9985]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hbb_tautau[0.9971]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_htautau_tautau[1.0047]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hgg_tautau[0.9974]"/>
  <Item Name="kappa_value_BR_HiggsDecayWidthTHU_hVV_tautau[0.9988]"/>

  <!-- Introducing nuisance parameter names -->

  <Item Name="QCDalphaS[0,-5,5]"/>
  <Item Name="BR_param_mB[0,-5,5]"/>
  <Item Name="BR_param_mC[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hbb[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hgg[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hVV[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_htautau[0,-5,5]"/>

  <!-- Introducing global observables -->
  <Item Name="QCDalphaS_In[0]"/>
  <Item Name="BR_param_mB_In[0]"/>
  <Item Name="BR_param_mC_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hbb_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hgg_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_hVV_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_htautau_In[0]"/>

  <!-- Introducing constraint terms -->
  <Item Name="RooGaussian::QCDalphaS_Pdf(QCDalphaS,QCDalphaS_In,1)" Type="constraint" NP="QCDalphaS" GO="QCDalphaS_In"/>
  <Item Name="RooGaussian::BR_param_mB_Pdf(BR_param_mB,BR_param_mB_In,1)" Type="constraint" NP="BR_param_mB" GO="BR_param_mB_In"/>
  <Item Name="RooGaussian::BR_param_mC_Pdf(BR_param_mC,BR_param_mC_In,1)" Type="constraint" NP="BR_param_mC" GO="BR_param_mC_In"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hbb_Pdf(BR_HiggsDecayWidthTHU_hbb,BR_HiggsDecayWidthTHU_hbb_In,1)" Type="constraint" NP="BR_HiggsDecayWidthTHU_hbb" GO="BR_HiggsDecayWidthTHU_hbb_In"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hgg_Pdf(BR_HiggsDecayWidthTHU_hgg,BR_HiggsDecayWidthTHU_hgg_In,1)" Type="constraint" NP="BR_HiggsDecayWidthTHU_hgg" GO="BR_HiggsDecayWidthTHU_hgg_In"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_hVV_Pdf(BR_HiggsDecayWidthTHU_hVV,BR_HiggsDecayWidthTHU_hVV_In,1)" Type="constraint" NP="BR_HiggsDecayWidthTHU_hVV" GO="BR_HiggsDecayWidthTHU_hVV_In"/>
  <Item Name="RooGaussian::BR_HiggsDecayWidthTHU_htautau_Pdf(BR_HiggsDecayWidthTHU_htautau,BR_HiggsDecayWidthTHU_htautau_In,1)" Type="constraint" NP="BR_HiggsDecayWidthTHU_htautau" GO="BR_HiggsDecayWidthTHU_htautau_In"/>

  <!-- Introducing response terms -->
  <Item Name="expr::expected_BR_param_alphaS_WW('pow(@0,@1)',kappa_value_BR_param_alphaS_WW,QCDalphaS)"/>
  <Item Name="expr::expected_BR_param_mB_WW('pow(@0,@1)',kappa_value_BR_param_mB_WW,BR_param_mB)"/>
  <Item Name="expr::expected_BR_param_mC_WW('pow(@0,@1)',kappa_value_BR_param_mC_WW,BR_param_mC)"/>
  <Item Name="expr::expected_BR_HiggsDecayWidthTHU_hbb_WW('pow(@0,@1)',kappa_value_BR_HiggsDecayWidthTHU_hbb_WW,BR_HiggsDecayWidthTHU_hbb)"/>
  <Item Name="expr::expected_BR_HiggsDecayWidthTHU_hgg_WW('pow(@0,@1)',kappa_value_BR_HiggsDecayWidthTHU_hgg_WW,BR_HiggsDecayWidthTHU_hgg)"/>
  <Item Name="expr::expected_BR_HiggsDecayWidthTHU_hVV_WW('pow(@0,@1)',kappa_value_BR_HiggsDecayWidthTHU_hVV_WW,BR_HiggsDecayWidthTHU_hVV)"/>

  <Item Name="prod::mu_BR_WW_composite(expected_BR_param_alphaS_WW,expected_BR_param_mB_WW,expected_BR_param_mC_WW,expected_BR_HiggsDecayWidthTHU_hbb_WW,expected_BR_HiggsDecayWidthTHU_hgg_WW,expected_BR_HiggsDecayWidthTHU_hVV_WW,mu_BR_WW_mod)"/>

  <Item Name="expr::expected_BR_param_alphaS_tautau('pow(@0,@1)',kappa_value_BR_param_alphaS_tautau,QCDalphaS)"/>
  <Item Name="expr::expected_BR_param_mB_tautau('pow(@0,@1)',kappa_value_BR_param_mB_tautau,BR_param_mB)"/>
  <Item Name="expr::expected_BR_param_mC_tautau('pow(@0,@1)',kappa_value_BR_param_mC_tautau,BR_param_mC)"/>
  <Item Name="expr::expected_BR_HiggsDecayWidthTHU_hbb_tautau('pow(@0,@1)',kappa_value_BR_HiggsDecayWidthTHU_hbb_tautau,BR_HiggsDecayWidthTHU_hbb)"/>
  <Item Name="expr::expected_BR_HiggsDecayWidthTHU_hgg_tautau('pow(@0,@1)',kappa_value_BR_HiggsDecayWidthTHU_hgg_tautau,BR_HiggsDecayWidthTHU_hgg)"/>
  <Item Name="expr::expected_BR_HiggsDecayWidthTHU_hVV_tautau('pow(@0,@1)',kappa_value_BR_HiggsDecayWidthTHU_hVV_tautau,BR_HiggsDecayWidthTHU_hVV)"/>
  <Item Name="expr::expected_BR_HiggsDecayWidthTHU_htautau_tautau('pow(@0,@1)',kappa_value_BR_HiggsDecayWidthTHU_htautau_tautau,BR_HiggsDecayWidthTHU_htautau)"/>

  <Item Name="prod::mu_BR_tautau_composite(expected_BR_param_alphaS_tautau,expected_BR_param_mB_tautau,expected_BR_param_mC_tautau,expected_BR_HiggsDecayWidthTHU_hbb_tautau,expected_BR_HiggsDecayWidthTHU_htautau_tautau,expected_BR_HiggsDecayWidthTHU_hgg_tautau,expected_BR_HiggsDecayWidthTHU_hVV_tautau,mu_BR_tautau_mod)"/>

  <Map Name= "EDIT::NEWPDF(OLDPDF,
    mu=mu_Htau,
    mu_BR_WW=mu_BR_WW_composite,
    mu_BR_tautau=mu_BR_tautau_composite,
    alpha_ATLAS_BR_tautau=zero,
    alpha_ATLAS_BR_tautauConstraint=one,
    alpha_Theo_alphas_Higgs_ggH_total=QCDalphaS,
    alpha_Theo_alphas_Higgs_ggH_totalConstraint=one,
       	       )" />
</Organization>

=== phreborn/vbfcp_comb/cfg/vv/qqqq_nominal.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization InFile="#INPUT#" OutFile="#OUTPUT#"
	     ModelName="llqq"
	     POINames="mu">
  <Item Name="one[1]"/>

  <Item Name="ATLAS_Jet_Scale1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_Jet_Scale1[0]"/>
  <Item Name="RooGaussian::ATLAS_Jet_Scale1Constraint(ATLAS_Jet_Scale1, nom_ATLAS_Jet_Scale1, 1)"/>

  <Item Name="ATLAS_LargeR_Res1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_LargeR_Res1[0]"/>
  <Item Name="RooGaussian::ATLAS_LargeR_Res1Constraint(ATLAS_LargeR_Res1, nom_ATLAS_LargeR_Res1, 1)"/>

  <Item Name="ATLAS_LargeR_Res2[0, -5, 5]"/>
  <Item Name="nom_ATLAS_LargeR_Res2[0]"/>
  <Item Name="RooGaussian::ATLAS_LargeR_Res2Constraint(ATLAS_LargeR_Res2, nom_ATLAS_LargeR_Res2, 1)"/>
  <!-- PDF -->
  <Item Name="EDIT::NEWPDF(OLDPDF,
	      alpha_ATLAS_JET_GroupedNP_2Constraint=one,
	      alpha_ATLAS_JET_WZ_Run1_pTConstraint=one,
	      alpha_ATLAS_JET_WZ_Run1_massConstraint=one,
	      alpha_ATLAS_JET_WZ_Run1_D2Constraint=one,
	      alpha_ATLAS_FATJET_JERConstraint=one,
	      alpha_ATLAS_FATJET_JMRConstraint=one,
	      alpha_ATLAS_JET_GroupedNP_2=ATLAS_Jet_Scale1,
	      alpha_ATLAS_JET_WZ_Run1_pT=ATLAS_Jet_Scale1,
	      alpha_ATLAS_JET_WZ_Run1_mass=ATLAS_Jet_Scale1,
	      alpha_ATLAS_JET_WZ_Run1_D2=ATLAS_Jet_Scale1,
	      alpha_ATLAS_FATJET_JER=ATLAS_LargeR_Res1,
	      alpha_ATLAS_FATJET_JMR=ATLAS_LargeR_Res2,
	      )"/>
</Organization>

=== phreborn/vbfcp_comb/cfg/run1_mass/DFD.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization InFile="workspace/combination/0130/mass/HSG12_2D_v04.root" OutFile="workspace/combination/0130/mass/HSG12_2D_v04_DFD.root"
             ModelName="DFD"
             POINames="mHiggs,DeltaM,mu_4l,mu_gamgam">
  <Item Name="DFD_e[1]"/>
  <Item Name="DFD_w[500]"/>
  <!-- EM_LatLeak -->
  <Item Name="ATLAS_EM_LatLeak_DFD_nuis[0,-5,5]"/>
  <Item Name="ATLAS_EM_LatLeak_DFD_gobs[0]"/>
  <Item Name="EXPR::ATLAS_EM_LatLeak_DFD_ConstraintPdf('1/((1+exp(@2*(@0-@3-@1)))*(1+exp(-1*@2*(@0-@3+@1))))',ATLAS_EM_LatLeak_DFD_nuis,DFD_e,DFD_w,ATLAS_EM_LatLeak_DFD_gobs)"/>
  <!-- EM_MatID_1 -->
  <Item Name="ATLAS_EM_MatID_1_DFD_nuis[0,-5,5]"/>
  <Item Name="ATLAS_EM_MatID_1_DFD_gobs[0]"/>
  <Item Name="EXPR::ATLAS_EM_MatID_1_DFD_ConstraintPdf('1/((1+exp(@2*(@0-@3-@1)))*(1+exp(-1*@2*(@0-@3+@1))))',ATLAS_EM_MatID_1_DFD_nuis,DFD_e,DFD_w,ATLAS_EM_MatID_1_DFD_gobs)"/>
  <!-- EM_MatID_2 -->
  <Item Name="ATLAS_EM_MatID_2_DFD_nuis[0,-5,5]"/>
  <Item Name="ATLAS_EM_MatID_2_DFD_gobs[0]"/>
  <Item Name="EXPR::ATLAS_EM_MatID_2_DFD_ConstraintPdf('1/((1+exp(@2*(@0-@3-@1)))*(1+exp(-1*@2*(@0-@3+@1))))',ATLAS_EM_MatID_2_DFD_nuis,DFD_e,DFD_w,ATLAS_EM_MatID_2_DFD_gobs)"/>
  <!-- EM_MatID_3 -->
  <Item Name="ATLAS_EM_MatID_3_DFD_nuis[0,-5,5]"/>
  <Item Name="ATLAS_EM_MatID_3_DFD_gobs[0]"/>
  <Item Name="EXPR::ATLAS_EM_MatID_3_DFD_ConstraintPdf('1/((1+exp(@2*(@0-@3-@1)))*(1+exp(-1*@2*(@0-@3+@1))))',ATLAS_EM_MatID_3_DFD_nuis,DFD_e,DFD_w,ATLAS_EM_MatID_3_DFD_gobs)"/>
  <!-- EM_MatID_4 -->
  <Item Name="ATLAS_EM_MatID_4_DFD_nuis[0,-5,5]"/>
  <Item Name="ATLAS_EM_MatID_4_DFD_gobs[0]"/>
  <Item Name="EXPR::ATLAS_EM_MatID_4_DFD_ConstraintPdf('1/((1+exp(@2*(@0-@3-@1)))*(1+exp(-1*@2*(@0-@3+@1))))',ATLAS_EM_MatID_4_DFD_nuis,DFD_e,DFD_w,ATLAS_EM_MatID_4_DFD_gobs)"/>
  <Item Name="const_unit[1]" />
  <Item Name="EDIT::NEWPDF(OLDPDF,
              ATLAS_EM_LatLeak=ATLAS_EM_LatLeak_DFD_nuis,
              ATLAS_EM_LatLeakConstraint=const_unit,
              ATLAS_EM_MatID_1=ATLAS_EM_MatID_1_DFD_nuis,
              ATLAS_EM_MatID_1Constraint=const_unit,
              ATLAS_EM_MatID_2=ATLAS_EM_MatID_2_DFD_nuis,
              ATLAS_EM_MatID_2Constraint=const_unit,
              ATLAS_EM_MatID_3=ATLAS_EM_MatID_3_DFD_nuis,
              ATLAS_EM_MatID_3Constraint=const_unit,
              ATLAS_EM_MatID_4=ATLAS_EM_MatID_4_DFD_nuis,
              ATLAS_EM_MatID_4Constraint=const_unit,
              )"/>
</Organization>

=== phreborn/vbfcp_comb/modVBFCP/smeftRun3Prospect/run3ProspGam/example.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization InFile="inWS/gamgam/Observed/vbf_cp_m0d00.root" OutFile="inWS/gamgam/Observed/vbf_cp_m0d00_run3Scale.root"
	      ModelName="HGam"
              POINames="mu,mu_Run3Scale,
                        mu_ggH,mu_ggH_SM,mu_VBF_RW,mu_VBF_SM"
              WorkspaceName="combWS"
              DataName="combData"
  >
  <Item Name="mu[1]"/>
  <Item Name="mu_Run3Scale[1]"/>

  <Item Name="mu_bkg_OO_TT_b1[1]"/>
  <Item Name="mu_bkg_OO_TL_b1[1]"/>
  <Item Name="mu_bkg_OO_LT_b1[1]"/>
  <Item Name="mu_bkg_OO_TT_b2[1]"/>
  <Item Name="mu_bkg_OO_TL_b2[1]"/>
  <Item Name="mu_bkg_OO_LT_b2[1]"/>
  <Item Name="mu_bkg_OO_TT_b3[1]"/>
  <Item Name="mu_bkg_OO_TL_b3[1]"/>
  <Item Name="mu_bkg_OO_LT_b3[1]"/>
  <Item Name="mu_bkg_OO_TT_b4[1]"/>
  <Item Name="mu_bkg_OO_TL_b4[1]"/>
  <Item Name="mu_bkg_OO_LT_b4[1]"/>
  <Item Name="mu_bkg_OO_TT_b5[1]"/>
  <Item Name="mu_bkg_OO_TL_b5[1]"/>
  <Item Name="mu_bkg_OO_LT_b5[1]"/>
  <Item Name="mu_bkg_OO_TT_b6[1]"/>
  <Item Name="mu_bkg_OO_TL_b6[1]"/>
  <Item Name="mu_bkg_OO_LT_b6[1]"/>

  <Item Name="prod::mu_composite(mu,mu_Run3Scale)"/>

  <Item Name="prod::mu_bkg_TT_b1_comp(mu_bkg_OO_TT_b1,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TL_b1_comp(mu_bkg_OO_TL_b1,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_LT_b1_comp(mu_bkg_OO_LT_b1,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TT_b2_comp(mu_bkg_OO_TT_b2,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TL_b2_comp(mu_bkg_OO_TL_b2,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_LT_b2_comp(mu_bkg_OO_LT_b2,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TT_b3_comp(mu_bkg_OO_TT_b3,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TL_b3_comp(mu_bkg_OO_TL_b3,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_LT_b3_comp(mu_bkg_OO_LT_b3,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TT_b4_comp(mu_bkg_OO_TT_b4,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TL_b4_comp(mu_bkg_OO_TL_b4,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_LT_b4_comp(mu_bkg_OO_LT_b4,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TT_b5_comp(mu_bkg_OO_TT_b5,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TL_b5_comp(mu_bkg_OO_TL_b5,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_LT_b5_comp(mu_bkg_OO_LT_b5,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TT_b6_comp(mu_bkg_OO_TT_b6,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_TL_b6_comp(mu_bkg_OO_TL_b6,mu_Run3Scale)"/>
  <Item Name="prod::mu_bkg_LT_b6_comp(mu_bkg_OO_LT_b6,mu_Run3Scale)"/>

  <Map Name= "EDIT::NEWPDF(OLDPDF,
              mu=mu_composite,
              mu_bkg_OO_TT_b1=mu_bkg_TT_b1_comp,
              mu_bkg_OO_TL_b1=mu_bkg_TL_b1_comp,
              mu_bkg_OO_LT_b1=mu_bkg_LT_b1_comp,
              mu_bkg_OO_TT_b2=mu_bkg_TT_b2_comp,
              mu_bkg_OO_TL_b2=mu_bkg_TL_b2_comp,
              mu_bkg_OO_LT_b2=mu_bkg_LT_b2_comp,
              mu_bkg_OO_TT_b3=mu_bkg_TT_b3_comp,
              mu_bkg_OO_TL_b3=mu_bkg_TL_b3_comp,
              mu_bkg_OO_LT_b3=mu_bkg_LT_b3_comp,
              mu_bkg_OO_TT_b4=mu_bkg_TT_b4_comp,
              mu_bkg_OO_TL_b4=mu_bkg_TL_b4_comp,
              mu_bkg_OO_LT_b4=mu_bkg_LT_b4_comp,
              mu_bkg_OO_TT_b5=mu_bkg_TT_b5_comp,
              mu_bkg_OO_TL_b5=mu_bkg_TL_b5_comp,
              mu_bkg_OO_LT_b5=mu_bkg_LT_b5_comp,
              mu_bkg_OO_TT_b6=mu_bkg_TT_b6_comp,
              mu_bkg_OO_TL_b6=mu_bkg_TL_b6_comp,
              mu_bkg_OO_LT_b6=mu_bkg_LT_b6_comp,
	             )" />
</Organization>

=== phreborn/vbfcp_comb/cfg/vv/qqqq_temp.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization InFile="workspace/vv/VVJJConfig/decorated/3000_HVT_WZ_decorated.root" OutFile="workspace/vv/VVJJConfig/modified/3000_HVT_WZ_largeR_modified.root"
	     ModelName="llqq"
	     POINames="mu">
  <Item Name="one[1]"/>

  <Item Name="ATLAS_Jet_Scale1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_Jet_Scale1[0]"/>
  <Item Name="RooGaussian::ATLAS_Jet_Scale1Constraint(ATLAS_Jet_Scale1, nom_ATLAS_Jet_Scale1, 1)"/>

  <Item Name="ATLAS_LargeR_Scale1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_LargeR_Scale1[0]"/>
  <Item Name="RooGaussian::ATLAS_LargeR_Scale1Constraint(ATLAS_LargeR_Scale1, nom_ATLAS_LargeR_Scale1, 1)"/>
  
  <Item Name="ATLAS_LargeR_Res1[0, -5, 5]"/>
  <Item Name="nom_ATLAS_LargeR_Res1[0]"/>
  <Item Name="RooGaussian::ATLAS_LargeR_Res1Constraint(ATLAS_LargeR_Res1, nom_ATLAS_LargeR_Res1, 1)"/>

  <!-- PDF -->
  <Item Name="EDIT::NEWPDF(OLDPDF,
	      alpha_ATLAS_JET_GroupedNP_2Constraint=one,
	      alpha_ATLAS_JET_WZ_Run1_pTConstraint=one,
	      alpha_ATLAS_JET_WZ_Run1_massConstraint=one,
	      alpha_ATLAS_JET_WZ_Run1_D2Constraint=one,
	      alpha_ATLAS_FATJET_JERConstraint=one,
	      alpha_ATLAS_FATJET_JMRConstraint=one,
	      alpha_ATLAS_JET_GroupedNP_2=ATLAS_Jet_Scale1,
	      alpha_ATLAS_JET_WZ_Run1_pT=ATLAS_LargeR_Scale1,
	      alpha_ATLAS_JET_WZ_Run1_mass=ATLAS_LargeR_Scale1,
	      alpha_ATLAS_JET_WZ_Run1_D2=ATLAS_LargeR_Scale1,
	      alpha_ATLAS_FATJET_JER=ATLAS_LargeR_Res1,
	      alpha_ATLAS_FATJET_JMR=ATLAS_LargeR_Res1,
	      )"/>
</Organization>

=== phreborn/vbfcp_comb/cfg/hcoup_ichep2016/add_theory_uncert.xml
<!DOCTYPE Organization  SYSTEM 'Organization.dtd'>
<Organization InFile="workspace/hsg2/H4l_STXS_13TeV_decorated.root"
	     OutFile="workspace/hsg2/H4l_STXS_13TeV_with_theory_uncert.root"
	     ModelName="theory_uncert"
	     POINames="mu, mu_gg2H_total_ZZ, mu_VBF_total_ZZ, mu_WH_total_ZZ, mu_ZH_total_ZZ, mu_ttH_total_ZZ">
  <!-- Signal strength parameters. Floating global signal strength and fix others to SM. -->
  <Item Name="mu[1,0,5]"/>
  <Item Name="mu_gg2H_total_ZZ[1]"/>
  <Item Name="mu_VBF_total_ZZ[1]"/>
  <Item Name="mu_WH_total_ZZ[1]"/>
  <Item Name="mu_ZH_total_ZZ[1]"/>
  <Item Name="mu_ttH_total_ZZ[1]"/>
  
  <!-- SM XSBR values -->
  <Item Name="XS13_gg2H_total_ZZ_SM[1.27231]"/>
  <Item Name="XS13_VBF_total_ZZ_SM[0.0990506]"/>
  <Item Name="XS13_WH_total_ZZ_SM[0.0359589]"/>
  <Item Name="XS13_ZH_total_ZZ_SM[0.0231493]"/>
  <Item Name="XS13_ttH_total_ZZ_SM[0.0132809]"/>

  <!-- Construct NP and global observables -->
  <Item Name="QCDscale_ggH[0,-5,5]"/>
  <Item Name="QCDscale_ggH_In[0]"/>
  <Item Name="QCDscale_qqH[0,-5,5]"/>
  <Item Name="QCDscale_qqH_In[0]"/>
  <Item Name="QCDscale_VH[0,-5,5]"/>
  <Item Name="QCDscale_VH_In[0]"/>
  <Item Name="QCDscale_ttH[0,-5,5]"/>
  <Item Name="QCDscale_ttH_In[0]"/>
  
  <Item Name="BR_param_alphaS_ZZ[0,-5,5]"/>
  <Item Name="BR_param_alphaS_ZZ_In[0]"/>
  <Item Name="BR_param_mQ_ZZ[0,-5,5]"/>
  <Item Name="BR_param_mQ_ZZ_In[0]"/>
  <Item Name="BR_HiggsDecayWidthTHU_ZZ[0,-5,5]"/>
  <Item Name="BR_HiggsDecayWidthTHU_ZZ_In[0]"/>
  
  <Item Name="pdf_Higgs_ggH[0,-5,5]"/>
  <Item Name="pdf_Higgs_ggH_In[0]"/>
  <Item Name="pdf_Higgs_qqH[0,-5,5]"/>
  <Item Name="pdf_Higgs_qqH_In[0]"/>
  <Item Name="pdf_Higgs_VH[0,-5,5]"/>
  <Item Name="pdf_Higgs_VH_In[0]"/>
  <Item Name="pdf_Higgs_ttH[0,-5,5]"/>
  <Item Name="pdf_Higgs_ttH_In[0]"/>

  <!-- Construnct constraint p.d.f. -->
  <!-- It is EXTREMELY IMPORTANT to include "ConstraintPdf" in the constraint pdf name, such that the code can identify it -->
  <Item Name="RooGaussian::ConstraintPdf_QCDscale_ggH(QCDscale_ggH, QCDscale_ggH_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_QCDscale_qqH(QCDscale_qqH, QCDscale_qqH_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_QCDscale_VH(QCDscale_VH, QCDscale_VH_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_QCDscale_ttH(QCDscale_ttH, QCDscale_ttH_In, 1)"/>
  
  <Item Name="RooGaussian::ConstraintPdf_BR_param_alphaS_ZZ(BR_param_alphaS_ZZ, BR_param_alphaS_ZZ_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_BR_param_mQ_ZZ(BR_param_mQ_ZZ, BR_param_mQ_ZZ_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_BR_HiggsDecayWidthTHU_ZZ(BR_HiggsDecayWidthTHU_ZZ, BR_HiggsDecayWidthTHU_ZZ_In, 1)"/>
  
  <Item Name="RooGaussian::ConstraintPdf_pdf_Higgs_ggH(pdf_Higgs_ggH, pdf_Higgs_ggH_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_pdf_Higgs_qqH(pdf_Higgs_qqH, pdf_Higgs_qqH_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_pdf_Higgs_VH(pdf_Higgs_VH, pdf_Higgs_VH_In, 1)"/>
  <Item Name="RooGaussian::ConstraintPdf_pdf_Higgs_ttH(pdf_Higgs_ttH, pdf_Higgs_ttH_In, 1)"/>

  <!-- Prepare response function -->
  <!-- Not sure how to consider the theory uncertainty correlation between signal and background. Leave it to experts to decide -->
  
  <!-- QCD scale uncertainties -->
  <!-- Format: function_name(NP_name,central_value,errHi,errLo,interpolation_code) -->
  <!-- N.B. the different convention with HistFactory: use uncertainty magnitude instead of variation boundary -->
  <Item Name="FlexibleInterpVar::response_QCDscale_gg2H(QCDscale_ggH,1,+0.046,-0.067,4)"/>
  <Item Name="FlexibleInterpVar::response_QCDscale_VBF(QCDscale_qqH,1,+0.004,-0.003,4)"/>
  <Item Name="FlexibleInterpVar::response_QCDscale_WH(QCDscale_VH,1,+0.005,-0.007,4)"/>
  <Item Name="FlexibleInterpVar::response_QCDscale_ZH(QCDscale_VH,1,+0.038,-0.031,4)"/>
  <Item Name="FlexibleInterpVar::response_QCDscale_ttH(QCDscale_ttH,1,+0.058,-0.092,4)"/>

  <!-- BR uncertainties -->
  <Item Name="FlexibleInterpVar::response_BR_param_alphaS_ZZ(BR_param_alphaS_ZZ,1,+0.0369,-0.0361,4)"/>
  <Item Name="FlexibleInterpVar::response_BR_param_mQ_ZZ(BR_param_mQ_ZZ,1,+0.0112,-0.0113,4)"/>
  <Item Name="FlexibleInterpVar::response_BR_HiggsDecayWidthTHU_ZZ(BR_HiggsDecayWidthTHU_ZZ,1,+0.0340,-0.0341,4)"/>
  
  <!-- PDF uncertainties: symmetrized. Use lognormal -->
  <!-- Not considering the correlation of alpha_S part with BR uncertainty here. Should be improved -->
  <Item Name="prod::response_pdf_gg2H(RooExponential::expTerm_pdf_gg2H(pdf_Higgs_ggH, expr::log_kappa_value_pdf_gg2H('log(1+@0)', uncert_pdf_gg2H[0.032])),nominal_pdf_gg2H[1])"/>
  <Item Name="prod::response_pdf_VBF(RooExponential::expTerm_pdf_VBF(pdf_Higgs_qqH, expr::log_kappa_value_pdf_VBF('log(1+@0)', uncert_pdf_VBF[0.021])),nominal_pdf_VBF[1])"/>
  <Item Name="prod::response_pdf_WH(RooExponential::expTerm_pdf_WH(pdf_Higgs_VH, expr::log_kappa_value_pdf_WH('log(1+@0)', uncert_pdf_WH[0.019])),nominal_pdf_WH[1])"/>
  <Item Name="prod::response_pdf_ZH(RooExponential::expTerm_pdf_ZH(pdf_Higgs_VH, expr::log_kappa_value_pdf_ZH('log(1+@0)', uncert_pdf_ZH[0.016])),nominal_pdf_ZH[1])"/>
  <Item Name="prod::response_pdf_ttH(RooExponential::expTerm_pdf_ttH(pdf_Higgs_ttH, expr::log_kappa_value_pdf_ttH('log(1+@0)', uncert_pdf_ttH[0.036])),nominal_pdf_ttH[1])"/>

  <!-- Finally prepare the replacement for current cross section handlers -->
  <Item Name="prod::XS13_gg2H_total_ZZ_with_uncert(mu, mu_gg2H_total_ZZ, XS13_gg2H_total_ZZ_SM, response_QCDscale_gg2H, response_pdf_gg2H, response_BR_param_alphaS_ZZ, response_BR_param_mQ_ZZ, response_BR_HiggsDecayWidthTHU_ZZ)"/>
  <Item Name="prod::XS13_VBF_total_ZZ_with_uncert(mu, mu_VBF_total_ZZ, XS13_VBF_total_ZZ_SM, response_QCDscale_VBF, response_pdf_VBF, response_BR_param_alphaS_ZZ, response_BR_param_mQ_ZZ, response_BR_HiggsDecayWidthTHU_ZZ)"/>
  <Item Name="prod::XS13_WH_total_ZZ_with_uncert(mu, mu_WH_total_ZZ, XS13_WH_total_ZZ_SM, response_QCDscale_WH, response_pdf_WH, response_BR_param_alphaS_ZZ, response_BR_param_mQ_ZZ, response_BR_HiggsDecayWidthTHU_ZZ)"/>
  <Item Name="prod::XS13_ZH_total_ZZ_with_uncert(mu, mu_ZH_total_ZZ, XS13_ZH_total_ZZ_SM, response_QCDscale_ZH, response_pdf_ZH, response_BR_param_alphaS_ZZ, response_BR_param_mQ_ZZ, response_BR_HiggsDecayWidthTHU_ZZ)"/>
  <Item Name="prod::XS13_ttH_total_ZZ_with_uncert(mu, mu_ttH_total_ZZ, XS13_ttH_total_ZZ_SM, response_QCDscale_ttH, response_pdf_ttH, response_BR_param_alphaS_ZZ, response_BR_param_mQ_ZZ, response_BR_HiggsDecayWidthTHU_ZZ)"/>


  <!-- PDF -->
  <Item Name="EDIT::NEWPDF(OLDPDF,
	      XS13_gg2H_total_ZZ=XS13_gg2H_total_ZZ_with_uncert,
	      XS13_VBF_total_ZZ=XS13_VBF_total_ZZ_with_uncert,
	      XS13_WH_total_ZZ=XS13_WH_total_ZZ_with_uncert,
	      XS13_ZH_total_ZZ=XS13_ZH_total_ZZ_with_uncert,
	      XS13_ttH_total_ZZ=XS13_ttH_total_ZZ_with_uncert,
	      )"/>
</Organization>
